### ISSUE TITLE
Validation error when generating certificate

### ISSUE THREAD

**Issue by jaroslavurban** [webprofusion/certify#124]
Any clue when I am receiving this validation error?

> Validation of required challenges did not complete successfully. Please ensure all domains to be referenced in the Certificate can be used to access  this site without redirection.

I was looking around but found nothing and the certify is bit of black box for me.  It could be related to more to LetsEncrypt, but as I use Certify tool, I want to double-check.

Thanks for any hints. Regards, Jaroslav

Some related details:
- using latest version of Certify
- on Winserver 2012, iis 8.5
- url for http with conf string is available, I double-checked that.

P.S> Maybe switch to Staging would be handy when facing some issue as limit for staging is 60 validation error per hour comparing to 5 for prod.

**Comment by webprofusion-chrisc** [comment]
Hi, there is a setting 'Enable Proxy API for domain config checks' which pings our server and asks it if it can see your /configcheck file. That service was failing for some of yesterday and has now been fixed.

This option exists because many IIS servers can either not see their own sites via DNS (so the config check fail) or they can see their sites but the public internet can't (so the config check passes but Let's Encrypt validation fails). I think there's a bug in the fallback checking mechanism for that.

**Comment by webprofusion-chrisc** [comment]
UI now contains an Info tab for managed site with a button to link back to Log, this explains which domain(s) have failed validation.
