### ISSUE TITLE
Unexpected problems with the certificates

### ISSUE THREAD

**Issue by NovichokAdmin** [webprofusion/certify#127]
![certify](https://user-images.githubusercontent.com/27774007/27958149-6514ec32-632a-11e7-87cf-b1b3a0852bb7.png)
[certify.docx](https://github.com/webprofusion/certify/files/1130963/certify.docx)

**Hi! The program is already a few months working on the server properly. But yesterday I started in a row to add new certificates. Everything went well until the straight pop up such errors , as shown in the attached file. Over time, I gave 20 certificates, and then went to this error.Please please help me with this problem.**

**Comment by webprofusion-chrisc** [comment]
The old version of certify didn't handle rate limits well which is why it's crashing. Let's Encrypt will only issue  20 certificates per domain per week so if many of your websites are subdomains of a single domain just wait a week to do more. If you use the new Certify and your domains are all setup as one IIS site (or grouped together into sites) you can manage up to 100 domains/subdomains per site as a single certificate.

**Comment by NovichokAdmin** [comment]
Thank you very much! So wait a week)
