### ISSUE TITLE
Changing the IIS Physical Path for a site breaks the renewal process

### ISSUE THREAD

**Issue by mpetito** [webprofusion/certify#146]
For our web applications, we use a deployment process which automatically re-configures IIS to point to a new physical path each time a deployment is performed.

We've noticed that renewing certificates with Certify fails if the physical path of the IIS site changes after it has been initially configured in Certify.

Steps to reproduce:

1. Configure a site in IIS with a physical path of [Path A]
2. Configure Certify to request a certificate for the IIS set (request succeeds)
3. Re-Configure the same IIS site to use physical path [Path B]
4. Attempt to renew the certificate for the site in Certify (request fails)

Expected: Certify would generate the .well-known directory under [Path B].
Results: Certify generates the .well-known directory under the original [Path A], which fails to pass the automated configuration checks.

Would it be possible to have Certify check for the current physical path of an IIS site at the time of renewal?

**Comment by Marcus-L** [comment]
As a workaround since you are already re-configuring IIS during deploy (and presumably have access to the IIS site identifiers), you could also have your deploy process update the Certify config in `C:\ProgramData\Certify\manageditems.json` via the IIS site ID (which is referred to as
"GroupId" in the config file) so that the auto-renewal would have the updated configuration.

**Comment by mpetito** [comment]
It looks like the ID in manageditems.json is actually a concatenation of some unique identifier and the IIS Site ID.  Reading through the json file to make the necessary updates certainly would be possible, but obviously not an ideal solution.

**Comment by webprofusion-chrisc** [comment]
Yes this has come up before and is especially relevant to those deploying using Octopus etc.  So when you have redeployed your site, what identifier would remain consistent between deploys in IIS? Until recently we relied on matching which site had which domain binding but this is risky if two sites exist with the same hostname binding. I was moving to using the IIS Site ID (which is a number) but I suspect in your case this will change between deployments and you will instead need to key on Site Name ('Default Web Site' etc), which for other users is potentially less dependable/durable than Site ID.

Likewise if we ever support other web server types we need a general key field to uniquely match site instances, rather than just matching on hostname bindings.

I think in your case it might make more sense for our CLI to have an option such as 'refreshmappings' which would take a named managed site and name IIS Site, then validates and updates that managedsite's www path settings and re-applies the latest cert/bindings to the site in IIS (rather than requesting a whole new cert).

I was thinking about generally using Site ID is the IIS key for a site and also updating the site path if it has changes (or even not storing it at all, always getting a fresh opinion).

**Comment by mpetito** [comment]
I am using Octopus Deploy deployments and the Site ID is preserved. It matches IIS sites by name during deployment and updates the existing site if found.

**Comment by webprofusion-chrisc** [comment]
Ok, thanks for this. The newest release now detects the website path dynamically if left blank in Advanced.
