### ISSUE TITLE
Feature: add filtering of site domains to Manage Site UI

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#157]
In the current Managed Site UI a single site could have many hundreds of domains/subdomains. It would be useful to be able to filter on keyword. It would also be useful to save this keyword in the managed site settings as some sites may only want to create a certificate for a specific subset of site domains. Another possible extension could be matching semicolon separated keywords e.g. 'testsite;livesite')

**Comment by vulwaowf** [comment]
I came here to write the same.

When I create a "new certificate", if the "Display Name:", eg. domain.com could be used to filter the DOMAINS in the list shown it would make it easier.  I don't know if making it automatic or adding a "filter" button beside the display name field would be better.  Adding semicolon separated keywords is also a great idea as the filter can be used to group certs that can be duplicated into one domain. eg. domain1;domain2 to find domain1.com and domain2.com in the list.

**Comment by webprofusion-chrisc** [comment]
Re-opening. This issue actually refers to the individual managed site UI, not the manage sites list.

**Comment by Marcus-L** [comment]
If adding the filter box next to the buttons (where else to put it?), should the behavior of the "select all" and "select none" buttons be changed to only affect the items being filtered?

![screenshot_110217_044757_pm](https://user-images.githubusercontent.com/1369184/32352087-b692b678-bfed-11e7-8ffd-5b2d2905d214.jpg)

**Comment by webprofusion-chrisc** [comment]
Yeah that's a tricky one. I'd say that select none removes all selection (even those filtered out), select all would select all visible items. We should save the filter also, and if non visible items are selected at save we'd need to warn, then unselect them.

The end result should be what you see is what you get.

**Comment by vulwaowf** [comment]
Marcus, the location of the Filter field you proposed is perfect.

I also agree with Chris, "select none" should remain as is and truly select none.  Because you can filter using a semicolon separated list you would never need to remove only a filtered set from a complete list.  People would use the filter to add to the selected groups of domains.

As for the Select All, when filtering name the "Select All" could become "Select Visible" or "Select Filtered".  Once you click the "Select Visible" the filter could be cleared and the view would be returned to the complete list with all domains showing.  Once a user clicks on "Select Visible" the assumption is that they are done with the filter operation.  This way you wouldn't need to add further functionality of warning users when SAVE is clicked.

**Comment by Marcus-L** [comment]
It sounds like @webprofusion-chrisc is suggested keeping the filter as a persisted setting, so it would always filter out things you didn't want to see in the list. However if I understand @vulwaowf's suggestion correctly, you'd like for the filter to be used as a tool for doing targeted bulk-select/deselection, and not save the filter to the site settings. Is that right?

**Comment by vulwaowf** [comment]
I came looking for progress on this and realized I didn't reply.  Sorry for the delay.  

Yes, I would be using it as a tool for targeted bulk-select/deselection.
-I don't mind typing the filter in every time to see filtered items.  That would be an added benefit if the filter was saved to the site settings.

Once I have created/used a filter I wouldn't use it again unless I was creating a new certificate or modifying a certificate which doesn't happen very often.
