### ISSUE TITLE
Enable Staging for testing

### ISSUE THREAD

**Issue by rolero** [webprofusion/certify#162]
Today I had an issue trying to renew a certificate in IIS 8. Renewal failed due to redirection.  Due to the fact I could not find the source of the redirection, I disabled the current web config. We have some rewrite rules to ensure users are forced to use https (SSL) and to hotlinking takes place. 

When I tried the renewal again I was not able to again due to the fact I hit the hourly rate (too many failed requests). Is there any way to use the testing/staging environment of Let's Encrypt. If not: Would be a great feature 👍

**Comment by webprofusion-chrisc** [comment]
Not currently an option (unless you compile yourself and use the debug build). This requires UI and some sort of warning/rollback (#163 ) because if the renewal then worked you'd be stuck with an untrusted (test) cert until you got past the rate limit.

The real solution for this particular issue is better configuration diagnostics in the app. (#92 )

**Comment by Marcus-L** [comment]
Currently the config checks (for http-01 and the tls-sni-01 in my branch) happen after the challenge has been requested but before it has been completed. Maybe we could add a "test" button to the "Advanced" tab that would simulate the actions performed by the challenge (adding the acme-challenge file for http-01 and self-signing a cert and installing the sni binding for tls-sni-01) and testing that, to avoid "burning" a cert request on the live server

**Comment by webprofusion-chrisc** [comment]
@Marcus-L thats exactly what I want to do with the diagnostic feature (bug link unavailable on my phone UI) whereby you can run checks for a site ad-hoc (or for all sites and get a report). So yes pulling that functionality out so it can be run outside of a request is a goal. Ideally it would optionally include the auto config step, so errors can be auto fixed.

**Comment by Marcus-L** [comment]
If you have a sec check out the commits at https://github.com/Marcus-L/certify/tree/tls-sni-challenge - I extracted out the validation test from the cert request process in commit https://github.com/Marcus-L/Certify/commit/da1b0be465b3bcdf40905c8cc54a128ef2bd2061:
![screenshot_092817_094138_pm](https://user-images.githubusercontent.com/1369184/30998639-d08de61a-a495-11e7-940c-a428314272ef.jpg)

If you want to try it out locally you'll have to pull the ACMESharp submodule from https://github.com/ebekker/ACMESharp/tree/8ab172e6262be29e60a89026c36adac16810cb3b, as [the PR](https://github.com/ebekker/ACMESharp/pull/295) is not yet merged into ACMESharp. Currently the standalone test does include the auto config step, if that option is set in the UI. Although from my testing TLS-SNI is preferable to HTTP for IIS 8+, because no modifications to the web.config are required (it is unfortunately not possible in IIS < 8). However I had to modify the `hosts` file to do test validation with the SNI binding using the .NET HttpClient, which potentially could cause errors.

**Comment by webprofusion-chrisc** [comment]
@Marcus-L Thanks, this is really more part of issue #92 , but that's a pretty monster change you've got going there! As an aside I did have the idea of having a Preview tab which would basically describe in English what the app plans to do next time  (or the first time) a request is ran - this would include a summary of the cert being requested and the changes/updates that the app will make to bindings (on which site etc), so this kind of heads in that direction as well.

**Comment by Marcus-L** [comment]
I know, sorry about adding that to the tls-sni branch. I needed to do testing for that though (where I found a big bug with the way I was checking SNI), so made sense to do it there. Hopefully the ACMESharp PR can get merged in, I think tls-sni-01 support in Certify will be great.

Getting back to the topic of this issue - I noticed that even using debug profile in Visual Studio currently doesn't change the LetsEncrypt endpoint to staging unless you create a new ACMESharp Vault, since the endpoint BaseUri is stored in the vault at create time.

**Comment by ravemir** [comment]
Bumped into the limits today and was wondering if we were able to use Certify with the staging environment, but only found this issue.

Is there a workaround we can use? I tried looking for the "ACMESharp" vaults, even under "\ProgramData\Certify\", but can't find anything with a "baseUri".

**Comment by webprofusion-chrisc** [comment]
@ravemir Hi, sorry we don't currently support the staging environment in our production build.

A workaround would be:
- clone the repo and build your own copy of the app in debug mode in visual studio. 
- copy over the debug Certify.Providers.Certes.dll into an install of the app on a server
- you would also need to update the contact under settings (can be same email) to recreate the account as a Staging account. 

To then restore the app back to production you'd need to restore the production Certify.Providers.Certes.dll and reset the contact again.

I'm interested in know what type of testing you are doing that hits a rate limit? Is renewal failing or are you creating many different certificates for something>

**Comment by ravemir** [comment]
I was working to develop a workflow where I'd deploy several machines from a template, with different hostnames, using the same wildcard certificate.

Since we had inbound network restrictions, we were using Route 53 as a validation method. In the documentation, "Route53FullControl" permissions were stated, but I had a feeling I could restrict it further and still have it work. After 5 requests, my tests were over.

We ended up foregoing wildcard certificates for the moment, but will need to be careful with our requests using the app the next time we pick it up. (or try to build the app in Debug mode, as suggested)

Thanks for the suggestion!

**Comment by webprofusion-chrisc** [comment]
@ravemir you may be interested in plans for the next version of the app, I'm planning a flexible (unlimited!) deployment tasks system with remote deployment, including deferred deployment (renew cert and configure deployment but then the actual trigger for the deployment is manual or scheduled).

**Comment by webprofusion-chrisc** [comment]
Implemented in v5 (beta), support for multiple certificate authorities and staging mode.
