### ISSUE TITLE
Improve pre-request config checks

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#165]
We now offer the option to manually test config, but the config check should really happen for every DNS identifier, on every request, as it may no longer be valid configuration (i.e. website has been deleted or domain no longer points to that site), or one domain might be properly mapped but the rest might fail (causing the whole request to fail overall).

We should change it so that config checks are ran before even attempting to register the identifier - currently some users run into failed authorization rate limits because of this.

**Comment by Marcus-L** [comment]
Good idea. I refactored the checks to verify the primary and all SAN domains, will send over a PR now. Clicking the "test" button in the UI does a simulated config check with mocked authorizations. But the config check that runs during cert requests (either from the UI or scheduled task) uses the real authorization key, so it can't be run before the identifier registration starts since the key is not yet available.
