### ISSUE TITLE
Failed to create scheduled task

### ISSUE THREAD

**Issue by nscherer** [webprofusion/certify#216]
I'm running Certify on an Amazon Web Services EC2 server.  Installation and renewal of certificates works just fine, however when I try to create a scheduled task, I get an error message "Failed to create scheduled task with given credentials".  I've tried with just "Administrator" and with "AMAZONA-U5R813C\Administrator" which is the username Remote Desktop Service uses to log in to this machine.  Is there an error log I can check for more detailed information?

**Comment by webprofusion-chrisc** [comment]
Hi, sorry we just use the TaskScheduler library to create tasks so the inner workings of that are where the diagnostics would occur. https://github.com/dahall/TaskScheduler

I'm in the process of moving the next version of the app to be a background service rather than a scheduled task.

It will be no consolation but I also have a couple of EC2 windows server (Server 2016) and they both work ok just using Administrator and the password (no domain prefix), so in your case I'd type your password into notepad to ensure the characters are typing as you expect.

**Comment by nscherer** [comment]
OK, thank you.
