### ISSUE TITLE
Optimisations for Exchange certs

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#221]
A very common use for https is for MS Exchange mail servers (outlook web access). Currently we're not optimised for this scenario. Likely optimisations so far are:

-  The ability to manually specify which domains to include in your certificate request
- The option to request the new cert and add it to the certificate store, but not update any IIS bindings etc.
- Change cryptographic provider for older versions of Exchange (see https://github.com/webprofusion/certify/blob/master/docs/Request%20Script%20Hooks.md)

Further notes for managing certs for exchange can be found here (for LEWS): https://github.com/Lone-Coder/letsencrypt-win-simple/wiki/Create-a-SAN-certificate-for-Microsoft-Exchange-2016,-2013-&-2010

**Comment by boscorelly** [comment]
Since the last december version, i had no problem wi exchange and certify =)

**Comment by webprofusion-chrisc** [comment]
Did you need to do anything specific to make it work or did you just use the default settings?

**Comment by boscorelly** [comment]
i was using default ssl settings, but now without it i think i will not be able anymore to request certs, because i a requesting certs on the reverse proxy, and mounting shares is too complicated each time...

**Comment by boscorelly** [comment]
Following exchange cert problem.

Were is the call to exchange script made please ?

**Comment by webprofusion-chrisc** [comment]
In v4 beta, your custom exchange script can be executed as a 'post-request' powershell script. First enable 'Show Advanced Options', which shows the Scripting tab. Then you can choose a preset script or point to your own script.

**Comment by webprofusion-chrisc** [comment]
For general scripting support info, see https://docs.certifytheweb.com/docs/script-hooks.html

**Comment by boscorelly** [comment]
I know but when i use your exchange script, how is it called/executed ? powershell -file ?

**Comment by webprofusion-chrisc** [comment]
@boscorelly we execute the given powershell script using the .Net System.Management.Automation library which creates a powershell "RunSpace" : https://github.com/webprofusion/certify/blob/development/src/Certify.Shared/Management/PowerShellManager.cs

This is more or less equivalent to running 'powershell -file' but is a little more integrated into the software.

**Comment by webprofusion-chrisc** [comment]
The main issue I see with the current approach of just asking the user to script something is that many of them will end up running a pre-built script they don't necessarily have a full understanding of. This will results in a variety of failures (different exchange version, options etc). My proposal is that we provide some amount of UI to simplify the process, but possibly having the resulting actions be run as scripts specific to different Exchange versions. So the question would be what options need to be presented in the UI and what does each version of Exchange require from a scripting point of view.

The aim is to have a process which is extremely simple and robust.

**Comment by tomchadwin** [comment]
@webprofusion-chrisc That would be perfect, assuming we don't have too many differing environments to cater for. Sounds like it should be achievable, though. I can help test for 2008R2/2010 (at the moment).

**Comment by webprofusion-chrisc** [comment]
@tomchadwin thanks! Yes, It seems common that people who are looking after an Exchange environment are usually only looking after one version, this leads to quite specific opinions as to how to solve the problem. I'm hoping to gather a few keen experts here so we can join all that knowledge up into one solution. 

I'm expecting to have time to dedicate to this over the next few weeks, so if I can gather enough help from real Exchange users that will help immensely. Ideally I want to offer an option where people can select the environments they are deploying to (e.g. Exchange 2010) and it will present them with necessary options. My assumption is that people are running the app on the same server as Exchange as otherwise we'd need to have remote execution etc.

I'm aware that some (all?) versions of exchange create default bindings in IIS which can cause a variety of  issues (such as a localhost binding, which we cannot generate certificates for).

**Comment by boscorelly** [comment]
Exchange 2010 support ends at 14 Jan 2020. Exchange 2019 will be released soon. I think only recent versions of exchange must be supported because exchange 2010 is not working sometime as newer versions.
Same for 2008r2.

defaults bindings in exchange are any hostname at 127.0.0.1:80/443 and any hostname at *:80/443.

I am creating a localhost binding because owa/eac are not working if not created with multiple server host names. In v3 the localhost is updated the same as others bindings. It doesn't need a valid san for localhost, it just need a cert. I always use the generated cert.

**Comment by Thayios** [comment]
I do not believe older versions should be supported as well. Once the cmdlets that operate to successfully import and assign the certificate end up expiring, I would say that would be the end of support (but maybe allow people to edit the cfg to update it manually).

I'm familiar with Exchange 2007 and upwards. The only deployment I have not done yet is 2019 because most organizations have moved to 365 now. I also have an MSDN/VS/WhateverTheyCallItNow subscription and ESX cluster, so I can spin one up with an external DNS if needed. 

In my opinion, the option should follow ISE's view. Allow people to manually put in the alternative names and such "just in case". The bindings for ECP and such run on different ports, so the original ports should be fine for IIS bindings.

My suggestion for procedure:
1) Stop Exchange
2) Generate new website folder with default bindings (or entered in options) with a hello world.
3) Import Generated Cert into Store of Computer
4) Run Cmdlet that is generated with the same thumbprint to assign services (which services question?). Ask to confirm that this indeed the right certificate thumbprint because if it's incorrect it will require manual intervention to pull the right stuff back in.
5) Shutdown generated website and delete it
6) Start IIS App Pools for Exchange
7) Check for right thumbprint via HTTPS check 
8) Confirm successful installation via an output of powershell (Get-ExchangeCertificate | Format-List FriendlyName,Subject,CertificateDomains,Thumbprint,Services  - Services cmdlet towards actual Windows Services).

**Comment by webprofusion-chrisc** [comment]
Does anyone know if you can still get trial versions of Exchange, to test against. Or even free cloud based labs/VMs?

**Comment by tomchadwin** [comment]
For those saying only support new versions, surely we should aim to support all non-EOL versions. That's the whole point of the product lifecycle, published years in advance. Drop support for versions once they are EOL, not before.

**Comment by Thayios** [comment]
@tomchadwin Yes, anything not EOL determined by Microsoft (or stats of usage, e.g. only 50 people every year use Exchange 2010 features, time to nick it as it's not worth the time of developers at that point to develop for a niche subset).

@webprofusion-chrisc Absolutely, I agree 100%.

**Comment by boscorelly** [comment]
@Thayios exch 2019 is not in public beta for as long as i know ;)
not need to stop iis at all.

@tomchadwin renewal is 3-5 years. If new standards and systems are implemented, too old systems will not be updated, resulting in lack of features.
Anyway, if you installed a 2008 in 2009, you have a 8 years old install, and you should really think about upgrading your systems as most of new applications (like exchange 2019) will not support less than 2012R2.

**Comment by boscorelly** [comment]
@webprofusion-chrisc you can install exchange without licence for 180 days. Installing exchange on adds server is not recommended, and you need at least 12Gb of RAM.

**Comment by webprofusion-chrisc** [comment]
Regarding old exchange versions, it just has to run on server 2008 r2 sp1 (64-bit) or higher, I think much of the UI would be similar, just the supporting scripts would change. For people with very advanced requirements standard scripting will still be an option.

**Comment by boscorelly** [comment]
some cmdlets change between 2010 and 2013+

**Comment by boscorelly** [comment]
opening Exchange Mamangement Shell : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command ". 'D:\Exchange\V15\bin\RemoteExchange.ps1'; Connect-ExchangeServer -auto -ClientApplication:ManagementShell "

**Comment by webprofusion-chrisc** [comment]
Closing. New exchange users should use the new Exchange deployment task in v5, Any bugs should be filed against that functionality. The option to use scripting still exists (as a Powershell deployment task).
