### ISSUE TITLE
Error message gets in the way of options

### ISSUE THREAD

**Issue by vulwaowf** [webprofusion/certify#255]
I am unable to close the error message that displays on the options panel if a domain authorization fails.  This usually would not be a problem, but with a smaller screen you cannot see the portion of the options panel that you need to work on.  The scroll bars with domain names are below the view.  The error also persists, closing the program doesn't make it go away.

There needs to be a dismiss button.

![certify - error message close feb8-2018](https://user-images.githubusercontent.com/30328500/35986623-8c92abfe-0cc7-11e8-8c43-3c04612d9d74.JPG)

**Comment by webprofusion-chrisc** [comment]
Thanks, this is resolved in the next version by making the message fixed height and scrollable. 

As a workaround you can either:

- delete and re-add your managed site, then use 'Test' under advanced to ensure your config works before making the real request to Let's Encrypt
- resolve your website configuration so that your certificate request works
