### ISSUE TITLE
Setting up a new certificate causes the wrong certificate to be served when there is a parent/child structure for the two sites

### ISSUE THREAD

**Issue by jasoncavett** [webprofusion/certify#288]
I will preface all of this that I am new to the management of certificates in IIS. I hope this is a simple issue and not a bug, but, in case it's not, I wanted to get the information down while it's still fresh in my head.

I have a number of websites I am hosting off of an IIS 10 server. I have successfully used Ceritfy 3.0.11.30336 to setup certificates for sites that exist both as separate sites and in separate physical locations on the disk. As an example:

example.com - `C:\inetpub\example.com`
example.net - `C:\inetpub\example.net`

Neither one shares a similar folder structure.

I also have sites setup that sit underneath the above folder structures. So...

example.org - `C:\inetpub\example.com\example.org`

This is something I inherited and I cannot change that structure readily right now.

When I add a new certificate to example.org, example.com starts serving up example.org's new certificate. This causes the wrong SSL certificate to be served and makes example.com inaccessible. I saw [the information in the FAQ](https://certifytheweb.com/docs/faq), but I don't think this is my case, though I'm not 100% sure.

When I setup example.org, I choose:

![image](https://user-images.githubusercontent.com/4645597/38714825-fdc4574a-3ea5-11e8-9707-a964fac7d26c.png)

I can provide more information as needed.

**Comment by webprofusion-chrisc** [comment]
Hi, you can send more detail sof your current IIS bindings etc through to me via email at: apps at webprofusion.com if you like, the most common reason for a certificate mixup would be where https bindings either share the same fixed IP (not set to All Unassigned) or one binding is not set to use SNI. 

Did you have pre-existing https on any of the sites? If so we just update the existing https binding rather than recreating it, and if it didn't have SNI enabled then you'd start to get issues.

**Comment by webprofusion-chrisc** [comment]
p.s. If in doubt, delete the https bindings in IIS for all variations, then choose Reapply Bindings under Advanced (per managed site), this will reconstruct the bindings (which should be Auto create) and re-apply the current cert.
