### ISSUE TITLE
SAN certificate. Incorrect sites selection

### ISSUE THREAD

**Issue by mikasoukhov** [webprofusion/certify#296]
I have the single web application in IIS bound with 2 domains (.com and .ru). Certify create SAN certificate for that two domain. I think it is definitely wrong. Cause I have several subdomains for each of root domains. And the best way for that is to create 2 SAN certificates.

I see the following solution. UI should provide an easy way to create a certificate (SAN and single). In where is user can put domains list. And only after that can provide manage IIS. So my point - detach certificate creation process from web server management.

With that process, you can provide extended certificate creation. For example, right now there is not any way to put company info (like legal address etc).

**Comment by webprofusion-chrisc** [comment]
You mention that your sites have several subdomains, this suggests to me that your IIS bindings are something like this:

- *.example.com (port 80)
- *.example.ru (port 80)

So you are looking to manually specify subdomains to include in your certificate, this is possible with v4 but I'd instead recommend switching to one or more wildcard certificates, To do that you would need to use DNS validation instead of http validation. We currently support Azure, Cloudflare and AWS DNS APIs (with v4).

For most users the simplest workflow is just to choose an exiting IIS site (with existing http bindings like www.test.com and test.com), then request the certificate (using the default http validation). However there are hundreds of possible combinations especially for advanced use cases (such as yours), so we're currently trying to find the best blend of UI to provide most use cases. Your feedback on the v4 UI would be appreciated: https://github.com/webprofusion/certify/issues/270

**Comment by webprofusion-chrisc** [comment]
Hi, we're constantly trying to make the user interface more intuitive but the task of creating certificates can be quite complex and confusing, so there's plenty of room for improvement in the future.

Both wildcard bindings and wildcard certificates are supported by IIS and have been for several years but if you find a problem please let me know.

We do not support any extended certification options (Address etc) as these are not supported by Let's Encrypt, they can technically be included in the certificate request but they will not include any of it in the resulting certificate they issue. For that you need an EV or OV certificate and these are only available from commercial certificate authorities who provide organisation validation. If you need that I would recommend purchasing wildcard certificates for your domains through someone like Comodo etc.

Regarding creating one certificate per domain, you should uncheck the domain you don't want to include, then create another Manage Certificate to cover the other domain. However if you are trying to cover subdomains on those domains then you need a wildcard certificate (or a certificate that covers all the subdomains, or one certificate per subdomain as well). It's easiest if you have a test server to try out the settings on, as it can take a bit of time to explore what the options do.

**Comment by mikasoukhov** [comment]
Well, my point was current UI is user unfriendly for guys who managed several domains (and who is willing to pay you to get commercial version). If you think that UI is OK, so let it be.
