### ISSUE TITLE
Certificate request fils with "Cannot server extensionless files"

### ISSUE THREAD

**Issue by Cambridgeport90** [webprofusion/certify#330]
I get this error message when using the latest version of Certify; only root domain and www are present; not trying to set up a wildcard. The site runs DNN if that might matter? I've never heard of it having anything to do with the certification authority, but I could be wrong on that. Any assistance would be wonderful; environment is Windows Server 2016 and IIS 10.0

**Comment by webprofusion-chrisc** [comment]
Hi Katherine,

Content Management System like DNN (and most others) often require a specific configuration of handlers in order to serve content with URLs that don't have an extension (so that content URLs don't need to end in .aspx or .php for example). At the same time the Let's Encrypt challenge response needs to create a file which has no extension and server it at /.well-known/acme-challenge in order to confirm control of the domain. This presents a problem in that often the CMS configuration fights with this requirement.

The solution is to configure the web.config of your DNN application to allow access to extensionless files in the /.well-known/acme-challenge path of your website, bypassing DNN. This is specific to your CMS and I don't have a default config to give you that will necessarily fix it for you.

The potentially easier alternative is to try out the new Http Challenge Server option in Certify v4 beta which is enabled by default. This temporarily sits in front of IIS and intercepts requests to /.well-known/acme-challenge

**Comment by Cambridgeport90** [comment]
Thanks. My friend was giving me a hand last night, and he figured out that it was actually supposedly due to www not being present in the verification string, or whatever the technical term is for it; give me a server to set up, but technicalities when it comes to TLS? Forget about it LOL. I really don’t yet know how to TLS, apparently.
