### ISSUE TITLE
Implement support for Azure Websites

### ISSUE THREAD

**Issue by webprofusion-chrisc** [webprofusion/certify#336]
Feature: Implement native support for Azure websites.

**Comment by mvanhalen** [comment]
What would be needed are 2 things. Using an Azure website a source to start like you do for IIS server now. and the second is applying the certificate to that same Azure website.
An extra nice would be to add web jobs to the same subscription which to care of the renewal automatically before the certificate expires after 90 days.

There is a letsencrypt extension for Azure websites. But its has some issue and does not work wilt wildcard SSL certificates. [https://github.com/sjkp/letsencrypt-siteextension](https://github.com/sjkp/letsencrypt-siteextension) 

Maybe we can make it part of the workflow. So that certify has a UI to point to the correct Azure website apply the extension but uses the validation of the certify too which works. What do you think. Maybe Azure website owners will be interested I think. Maybe even Microsoft themselves.

**Comment by sjkp** [comment]
By all means add support to azure web site to your product, I have no problem with that, and that would be a great idea. And I'm sure Microsoft would love any help they can get, from my understanding the reason why we haven't seen official Lets Encrypt support in azure is due to some internal politics of who should own the feature, as SSL and security is not owned by the web app team, which are the ones that would benefit the most from it. 

You can borrow as much as you want from the letsencrypt extension, but don't expect me to do any work in the certify product (I call it a product as it has a paid plan).

**Comment by webprofusion-chrisc** [comment]
Thanks folks, when I get time after the v4 initial release I'll look at this in more detail but feel free to itemise any steps you think are required/helpful.

@sjkp thanks, I think there will always be a need for custom scripting like yours to address specific scenarios and I doubt we'll every cover every use case. This project exists solely to make certificate things simpler to do. Yes Certify is a commercially supported open source product however the vast majority of users just need/use the free version and that will probably always be the case. Code contributors get a free license for the pro version if they want it.

**Comment by sjkp** [comment]
When it comes to the Azure Implementation, there is unfortunately a lot of ways that people can do things, which makes adding support for letsencrypt not straight forward. Adding support for wild card just makes things worse, as people might use many different dns providers, ofc adding support for azure dns would be priority 1, but I'm guess that there is a lot people who don't use azure dns. 

Here's just a short list from the top of my memory of things to consider with azure web app support. 

* Azure web apps host many different types of apps, node, java, python, C#, go etc. this means relying of web.config and placing files in /.well-known doesn't just always works as people might have setup their web server to not serve files from that location (a fair amount of my issues have been due to this) 
* People don't understand how lets encrypt works, and rightfully doesn't really care, but when using the http challenge, they need to understand that files must be served out of their web app, so they can't just put authentication on everything or force https 
* Some people use the caching feature of web apps, it messes with extension like mines ability to write to disk 
* If things are to be automated people need to use a service principal and grant it access to the right azure resources (this part have cause people a lot of frustration) 
* I did a mistake when I created the site extension with the web job embedded in the site the certificate was to be issued for, this web job should have been external to the web app (as people accidentally delete the job)  
* Azure is not as coherent as one would hope, the regional data centers use their own url sets etc 
* Scale some people wants to use lets encrypt certificates for hundreds of sites, I'm guessing re-sellers or CMS systems providers, Azure ARM backend is really slow (or at least was) when comes to dealing with many certificate

**Comment by webprofusion-chrisc** [comment]
@sjkp thanks for the advice and information Simon, I think initially we would be best to only support DNS validation because as you say the extensionless config for .well-known creates a lot of confusion, and we need to support various DNS providers anyway (for wildcard cert requests).

**Comment by mvanhalen** [comment]
Thanks for the input @sjkp 

I think DNS is best as well for a main validation method. Especially because many options/providers are supported already. Although we could maybe add a semi automatic option as well. For DNS and .well-known files where the user uploads that file itself, or add the DNS txt entry manually. Then all cases are covered. Not all webmasters can upload files or have access to DNS settings. But for now we can focus on the DNS method first.

A question the validation is needed each time? Also for renewals? Is a new package .well-known or DNS txt record needed every renewal?

I can work with code from @sjkp Might have some questions about certain things while starting to work with it.

**Comment by sjkp** [comment]
I would recommend that you look at the https://github.com/fszlin/certes his implementation is really nice. I'm in the process of changing to that in the azure lets encrypt site extension. But yes for the dns challenge the dns txt record value changes every time you renew.

**Comment by webprofusion-chrisc** [comment]
Certify (v4, the current development version) uses Certes as well, with an aim to also support AcmeSharpCore in the future.

@mvanhalen validation is required for every new certificate order, which basically means it's required every time. For Let's Encrypt renewals are the same as a new certificate request.

The question would be where does the processing take place? Currently Certify The Web runs a background service on the users computer or server in order to perform periodic certificate renewal and most importantly to store the configuration for the certificate request (including secrets such as DNS API credentials). 

The simplest way to adapt Certify would be to have the same (or nearly the same) background service perform the certificate request and then deploying the certificate to azure. The background service currently runs a locally bound web api and a signalr hub to talk to the client UI. Perhaps this can be made to run as a continuous web job (I haven't used Azure web jobs so I don't know what their limitations are), then UI would need to connect to the appropriate instance in order to administer/report on the relevant managed certificates.

The purpose of Certify is to greatly simplify configuration/setup and to make renewal reliable (or failure recoverable), but it does raise the question of whether involving Certify The Web at all is a good idea (as you could instead just use Certes etc in an azure web job directly). The main benefit of having Certify run the show is that it has an administrative UI, diagnostic tools and recovery mechanisms, but it does need regularly updated (as does the background service), so this would need to be taken into account.

**Comment by mvanhalen** [comment]
That is a nice library indeed. I see a role for Certify to install some or 1 webjob (s) to Azure and control your certificates in an easy way and read the Azure website for the domain used and stuff. An administrative GUI indeed.  I have asked a Microsoft Azure employee  (don´t know his Github handle) on what is happening on their side and Letsencrypt. I will get back when I have some more feedback.

**Comment by MichelZ** [comment]
I would even be happy when a job on another computer takes care of the deployment (no need to run jobs in azure web apps), e.g. the Windows version requests certificate and then uploads/binds to App Service.
Might be an easier short-term-goal?

**Comment by MichelZ** [comment]
I guess there has been no progress here?

**Comment by webprofusion-chrisc** [comment]
@MichelZ Hi, no progress on this currently. There is a back log of features/bugs and this hasn't bubbled to the top yet. Very keen for PRs though but would need to discuss the approach before any serious work was done.

**Comment by MichelZ** [comment]
Thanks, I might take you up on this if my needs get serious enough :)

**Comment by webprofusion-chrisc** [comment]
Some related resources: 

http://encamina.com/articulos_tecnicos/english/How_to_generate_Lets_Encrypt_SSL_Certificates_with_Azure_Automation.pdf

https://www.hanselman.com/blog/SecuringAnAzureAppServiceWebsiteUnderSSLInMinutesWithLetsEncrypt.aspx

Still up for debate is what value Certify would bring to the process as it's external to Azure itself and would probably need to be a module you install in Azure. Would Certify be easier than the current approaches mentioned above and if so how?

**Comment by MichelZ** [comment]
These are weird hacks for me, and nowhere as comfortable as Certify. I'd like either native integration by Azure itself (how the hell is this not a thing yet???), or by Certify - my easy-to-use-go-to-solution :)

**Comment by webprofusion-chrisc** [comment]
Belated update: Certify does now have deployment tasks to deploy directly to Azure App Service (webapp or function) or to Azure KeyVault. We've had the KeyVault support for a long time but the app service feature is fairly recent.
