### ISSUE TITLE
Test Progress Window partially hidden by Preview window

### ISSUE THREAD

**Issue by miranoff** [webprofusion/certify#338]
If you click the test button on a domain while you have the Preview screen selected, the preview screen covers part of the black test progress screen.

**Comment by webprofusion-chrisc** [comment]
Thanks, I have noticed this before as well. The issue is that the embedded internet explorer control (used to view the markdown document for the preview) is rendered outside the WPF stack. I've played with hiding it dynamically but that didn't behave very well. The most likely workaround for this will be changing the tab back to status (or domains) when Test is selected.
