### ISSUE TITLE
wildcard support with windows dns server

### ISSUE THREAD

**Issue by tester-02** [webprofusion/certify#343]
After adding domains like domainexample.com, *.domainexample.com, anotherdomain.org, *.anotherdomain.org, ... I have to use the manual dns verifikation. So for every domain I got two different challenges. One for the fully qualified domain name and the second for its wildcard.

On a windows maschine with the windows dns server I have for both challenges only the same ONE entry:
_acme-challenge.domainexample.com
Therefore I run into trouble because one of the two challenges will fail by default, since I can't run them one after the other. 
So I would like to have the possibility to select for which domainnames I want to complete the callenge, that I'll get the chance to change the dnsvalue between each check.

**Comment by webprofusion-chrisc** [comment]
Hi, we should create/update documentation for this but this is expected behaviour. To request a certificate covering both a wildcard and the root level domain requires two validations fron Let's Encrypt. Each one  will have different values but as you say they will both have the same record name. I have previously raised this as an issue and cause for confusion with Let's Encrypt via their community but it seems nobody else agreed with me. The only way to make it work is to have a TXT record with multiple values, therefore each call to create a record should be additive to existing values. A delete call will also be made once validation completes but this will occur twice (once per domain validation) so your script needs to allow for records that don't exist any more.

**Comment by webprofusion-chrisc** [comment]
As a workaround you will find that although the certificate request fails initially, it will eventually work as each challenge is completed.

**Comment by crza** [comment]
multiple TXT records are a feature.
https://tools.ietf.org/html/rfc1464

At least my linux nameserver and my DNS-hoster supports this.
Is this a limitation for Windows DNS Server or a bug?

**Comment by webprofusion-chrisc** [comment]
@crza yes indeed, multi value TXT records are fine, I'm sure windows DNS supports them. The point is that reusing the same challenge record name for both the wildcard and root level domains means you have to eventually clean up (i.e. delete or remove values from) the txt record. That's a destructive action made worse (even potentially catastrophic) if you have bugs in your delete method. This would be unnecessary if wildcard validation optionally allowed a slightly different TXT record name (such as __acme-challenge.subdomain) for the wildcard validation.

**Comment by mb300sd** [comment]
See #348 and see if my scripts work for you. I had no issues verifying multiple domains with wildcards.

**Comment by webprofusion-chrisc** [comment]
Closing, as this is specific to how a given custom script handles DNS updates.
