### ISSUE TITLE
Support Microsoft DNS

### ISSUE THREAD

**Issue by mb300sd** [webprofusion/certify#348]
Supporting the MS DNS server naively would be nice, I'm surprised it's not already included consider Certify is developed in .NET. I'm currently working on a powershell script to do so, but of coarse native support is cleaner.

**Comment by mb300sd** [comment]
In case anyone else is looking for a solution.

CertifyCreate.cmd (add this in interface)
`cd /D "%~dp0"
powershell -File CertifyCreate.ps1 %1 %2 %3`

CertifyCreate.ps1
`$zone = $args[0]
$full = $args[1]
$challenge = $args[2]

$name = $full -replace ".$zone$"

Add-DnsServerResourceRecord -ComputerName Server-DC -ZoneName $zone -Name $name -Txt -DescriptiveText $challenge -AgeRecord`

Create a new domain account
Add it to DnsAdmins on the domain.
Add it to local Administrators group on the web server.
Set the Certify service to run under that account.

I didn't bother creating a remove script since record aging will remove it within a week.

**Comment by webprofusion-chrisc** [comment]
Nice! 

As a side note, for wildcard domains and root level domains (e.g. *.test.com and test.com) Let's Encrypt requires validation against a TXT record of the same name (e.g. _acme-challenge.test.com) with multiple values. 

So in order to create a certificate that covers both *.test.com and test.com (because *.test.com does not count for test.com, confusingly) you technically need to update the TXT record value with an additional value, rather than overwriting it. This leads to having a TXT record with many values over time.

You can get it to work without because validation will fail for one variant, then work for the other and when the request re-tries the other validation will also complete.

**Comment by mb300sd** [comment]
The script actually never overwrites or deletes records. It sets the Windows DNS server's built in expiry and let's that take care of it, so both records do get created for wildcard domains.

**Comment by webprofusion-chrisc** [comment]
@mb300sd awesome!

**Comment by mb300sd** [comment]
Could we pass the zone name from the UI as a 4th argument to the script? Right now there's no way to code the it to work if the zone in the server is x.something.com instead of something.com going back and forth to the server to check if each level of subdomain exists.

**Comment by webprofusion-chrisc** [comment]
@mb300sd yes, you should find that the 4th parameter (if you use it in your script) is indeed the zoneid (which is usually either the name of the root level domain or a code for the zone depending on the DNS API). Incidentally you can actually just type into the zoneid box when configuring the DNS scripting part, the lookup '...' is just for providers that support it and we should probably try to hide that functionality (just leave  the text box for entry).

**Comment by webprofusion-chrisc** [comment]
@AdamantUK yes, it's not a great technical challenge - the reason is that we do not have the resources to create DNS API Providers for every DNS API, so we just do the most requested/common ones and we also accept user contributed DNS providers. Several of our DNS providers were contributed by third parties, which was great.

Please do contribute the provider if you can, here are our current examples to follow: https://github.com/webprofusion/certify/tree/development/src/Certify.Providers/DNS

**Comment by AJH16** [comment]
I actually ended up reworking it to be Cim based as this has better performance apparently.  It also can go through .Net Standard so I will likely end up changing the project type over to match the rest of the DNS providers once I get things working all the way.

**Comment by webprofusion-chrisc** [comment]
That sound great! Yes all our libraries are currently .net standard 2.0 so I would make that change for you if merging it in. I'll check out your branch to see how it's going!

**Comment by webprofusion-chrisc** [comment]
@AJH16 jast as feedback, I noticed that you're doing domain name splitting based on count of components (when setting 'Container'), this usually doesn't work out that well (for domains like example.co.uk or subdomain.exmaple.co.uk) and suggests that you do have a 'zone' concept, so you should let the user pick the zone to add the record to. 

The `DnsProviderBase` class has some helper methods to work out which part of the domain needs to be truncated from the recordname depending on whether your zone is a subdomain or not. (so if your zone is for subdomain.example.co.uk and the record is `_acme-challenge.www.subdomain.example.co.uk` it knows the 'normalized' record name to create is `_acme-challenge.www`

**Comment by AJH16** [comment]
Cool, I'll take a look at that.  Glad you have something better to work from.  I knew that part was spotty.  Another thought was just to use the zone list query and just keep adding parts until it gets a zone match.  I was more focused on getting the connectivity working first though and then work on the remainder of the cleanup.

I was also thinking about doing a bit of trying to cleanup the password parameters to use a SecureText directly and use a passwordbox and maybe try to add a dropdown parameter option, but my XAML experience is non-existent (I'm a backend framework architect, not a UI guy.)  The string matching on the auth type bugs me though.

**Comment by webprofusion-chrisc** [comment]
@AJH16 I think it's a great start and is probably already in a good position, if you can test it working for you then I'd be happy to merge it into a beta version for people to try out. I'm investigating setting up a test windows DNS zone to try it out as well. 

One of the tricky parts of having many DNS providers is trying to test them all, and if developing a provider requires setting up a paid account with a DNS provider, it's probably just not going to happen (currently) unless the user develops the provider themselves (there are many examples of this).

In general I see DNS API's a a necessary evil currently, they are quite dangerous as a concept (bug or vulnerability exposes the enter DNS account) and some other big clients don't even encrypt the credentials on disk.

The bigger picture plan is to provide a one-stop method to delegate validation via one-time creation of a CNAME record per domain:
https://github.com/webprofusion/certify/issues/369

**Comment by AJH16** [comment]
Hmm, that's pretty cool.  Didn't realize that they allowed CNames to follow through.  On the one hand it's handy on the other hand it seems like it counteracts a lot of the purpose of redoing validation rather than just having persistent validation keys like Google does for claiming a site.  Not sure why, if they are willing to follow a permanent CName, they aren't also just willing to make setting the validation code once a thing.

**Comment by webprofusion-chrisc** [comment]
It's (potentially) a permanent CNAME but the TXT record it eventually resolve to will need to be up to date with the correct challenge response text. It's also possibly that if it was fully explored the idea may have other disadvantages, to my knowledge it's not a technique being used on a grand scale yet.

**Comment by AJH16** [comment]
Right, I get that the record the CName points to still has to be the latest, but at that point you aren't actually authenticating anything.  Just that the delegated party hasn't been revoked, which you can still get from checking if the old validation code is still up.  You don't have any knowledge of current control of the domain being validated, so there's no point (that I can see anyway) in bothering to change the validation code at that point.  It's a perfectly valid use case not to care.  Google's analytics claim keys don't change and work just fine.  A permanent DNS validation key would work just as well as the CNAME as it is still easily removed by an attentive DNS admin and both are equally vulnerable to allowing persistent access after access to a domain has been cut off if the admin isn't paying attention.
