### ISSUE TITLE
Run powershell from dns custom scripts

### ISSUE THREAD

**Issue by mb300sd** [webprofusion/certify#349]
Right now it only seems to be compatible with batch files or exes. It would be nice to be able to use powershell.

**Comment by webprofusion-chrisc** [comment]
Hi, the idea behind using the command prompt is for broad compatibility, you can invoke powershell scripts as normal using the 'powershell' command.

**Comment by npodbielski** [comment]
For now it do not work at all. 
I tried to use: 
c:\path\script.ps1
c:\\path\\script.ps1
powershell -file c:\path\script.ps1
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -file C:\path\script.ps1
C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -file C:\\path\\script.ps1
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -file C:\path\script.ps1"
"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -file C:\\path\\script.ps1"

None of this works. I think there is kind of problem how script is invoked vie ProcessInfo class. In the end if this would be Python, PHP or Perl script it should does not matter since it works via windows explorer, right? But it does matter. It would be nice if you could at least provide example how to correctly run this PS script from your application since it is, as you see above completely not intuitive.

**Comment by npodbielski** [comment]
I also tried bat file with following contents:
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -file c:\path\script.ps1 %1 %2 %3`
Something that work without a problem from command line, via CTW I got:

`(Use Custom Script) :: 
Error: iwr : The response content cannot be parsed because the Internet Explorer engin
Error: e is not available, or Internet Explorer's first-launch configuration is not co
Error: mplete. Specify the UseBasicParsing parameter and try again. `

Which is kinda good. At least I got PS working. Bad thing is that CTW seems to run programs as a different user then mine. This means I can't easily store credentials. I cannot use CTW credentials store because it do not support for 'custom' credentials. Well this sucks.

**Comment by npodbielski** [comment]
Ok I changed user of CertifyTheWeb Service to mine user. And finally got working PS script. 
At least you could provide some example how to do it without forcing user to hack through it by himself. :)

**Comment by npodbielski** [comment]
Also post certification scripting *have* to be PS script so somehow CTW *know* and *can* run PS scripts. But not during DNS update. Hm...

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for raising this issue.

We have some docs for DNS scripting which I'd be happy to add to if you have specific instructions you feel are missing: https://docs.certifytheweb.com/docs/dns-scripting.html - as noted there the script should be a batch file (.bat) and will run as the background service (local system). Personally I don't recommend changing the user of the background service as you will have to then debug permissions problems.

**Comment by npodbielski** [comment]
Damn... My first try was around 3 months ago and I was looking for some instructions like that. I did not found link above. Too bad since it would solve all of my problems probably. 
Anyway thanks. I tried yesterday and it worked CTW successfully updated certificate.
