### ISSUE TITLE
Should upgrades be required?

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#350]
I have several servers running V3.0.11.  Normally when any new product update is released, I only install the update on a single server for testing purposes before releasing it environment-wide to ensure everything works as it should.  With Certify though, it seems we're required to upgrade the software in order to continue using it, even though v3.0.11 still works properly.  

I understand if bugs come up in older versions, the first thing said is that you need to upgrade because the product isn't supported anymore.  I also understand from the development standpoint, forcing the upgrade keeps one platform that you have to maintain, but that's frustrating for the end users.  In my personal life, I don't mind being on the "bleeding edge", but in my work life, I like to let other people find the bugs (not that this will have any bugs...).

**Comment by webprofusion-chrisc** [comment]
Hi, is the app saying you have to upgrade? You should be able to stay on 3.0.11 if you're happy with it.

**Comment by kd8ssq** [comment]
Yeah it is.  If you click “No” that you don’t want to upgrade, you get a
dialog stating that this version of the app is not supported, then the app
closes.

**Comment by webprofusion-chrisc** [comment]
Thanks for reporting this, it's now fixed. The update mechanism has a flag to force upgrades if there is a major issue, this was incorrectly set to try because the previous beta version had to upgrade between each version. So, you do not need to upgrade from 3.0.11.

**Comment by kd8ssq** [comment]
Great!  Thanks!

**Comment by davegambino** [comment]
It is forcing me to upgrade.  
		
		

		Get Outlook for iOS
	




On Tue, Jul 31, 2018 at 6:39 PM -0500, "Christopher Cook" <notifications@github.com> wrote:












Hi, is the app saying you have to upgrade? You should be able to stay on 3.0.11 if you're happy with it.

**Comment by davegambino** [comment]
But what if I want to upgrade.   What are the correct steps?
Th error message says I need to uninstall first.    I think it would be helpful if you put very specific update notes on the website.   Most people who will be updating have many sites on a production environment and want to be very cautious.  Thanks.  Dave
		
		

		Get Outlook for iOS
	




On Tue, Jul 31, 2018 at 7:00 PM -0500, "Christopher Cook" <notifications@github.com> wrote:












Thanks for reporting this, it's now fixed. The update mechanism has a flag to force upgrades if there is a major issue, this was incorrectly set to try because the previous beta version had to upgrade between each version. So, you do not need to upgrade from 3.0.11.

**Comment by webprofusion-chrisc** [comment]
@davegambino yes I do think we need to guide people to upgrade instructions, specifically I would advise taking backups of your c:\programdata\certify folder in case you need to revert for any reason. 

I agree regarding production servers. I would suggest you don't upgrade unless you definitely need a new feature and I would also suggest you try it out first on a test server, not a production server.  This version is significantly different and and may take a little getting used to.

The error message regarding 'A 32-bit version of this app already exists, please uninstall first' should be self explanatory and if it's not I would strongly advise getting a professional IT support person to look after your servers. While we all like to be able to do/look after things ourselves sometimes it's worth getting a few hours of help from experts, especially if there are various factors that could make things complicated. SSL on Windows can sometime be simple but is very often complicated at exactly the moment you don't want complications.

**Comment by davegambino** [comment]
If the previous version is unistalled, will the necesssary setting remain on the n tact?    Will future upgrades require unstialls?

Thanks again.  Dave

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by davegambino** [comment]
Do you mean c:\programfiles\certify?



*Dave Gambino*

dave@smbcreativegroup.com

1-800-980-0906 x 705

 [image: Linkedin-logo] <https://www.linkedin.com/in/davegambino>

*SMB Creative Group*

www.SMBCreativeGroup.com <http://www.smbcreativegroup.com/>



*Our Services*

www.CatholicChurchWebsites.com <http://www.catholicchurchwebsites.com/>



*From:* Christopher Cook [mailto:notifications@github.com]
*Sent:* Tuesday, July 31, 2018 11:26 PM
*To:* webprofusion/certify <certify@noreply.github.com>
*Cc:* SMB <dave@smbcreativegroup.com>; Mention <mention@noreply.github.com>
*Subject:* Re: [webprofusion/certify] Should upgrades be required? (#350)



@davegambino <https://github.com/davegambino> yes I do think we need to
guide people to upgrade instructions, specifically I would advise taking
backups of your c:\programdata\certify folder in case you need to revert
for any reason.

I agree regarding production servers. I would suggest you don't upgrade
unless you definitely need a new feature and I would also suggest you try
it out first on a test server, not a production server. This version is
significantly different and and may take a little getting used to.

The error message regarding 'A 32-bit version of this app already exists,
please uninstall first' should be self explanatory and if it's not I would
strongly advise getting a professional IT support person to look after your
servers. While we all like to be able to do/look after things ourselves
sometimes it's worth getting a few hours of help from experts, especially
if there are various factors that could make things complicated. SSL on
Windows can sometime be simple but is very often complicated at exactly the
moment you don't want complications.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/webprofusion/certify/issues/350#issuecomment-409445174>,
or mute the thread
