### ISSUE TITLE
NameCheap DNS validation

### ISSUE THREAD

**Issue by xxbiohazrdxx** [webprofusion/certify#376]
Hi there. I'm currently using a custom script to handle this, but it seems like it would be relatively easy to implement DNS validation for NameCheap. Their API is pretty straightforward.

https://www.namecheap.com/support/api/methods/domains-dns.aspx

**Comment by webprofusion-chrisc** [comment]
Hi, thanks for your request. Adding more DNS providers is definitely on the list of things to do, and generally they're quite similar. 

It's just a matter of  spending development time on it, and I'm very time poor :( we'll get there eventually though! I'm also considering ways to add more DNS APIs without having to update the client software every time.

**Comment by impworks** [comment]
I'm working on this right now. Will take about a week, because even getting an API access requires a review from NameCheap that takes up to 2 business days.

**Comment by webprofusion-chrisc** [comment]
Thanks! Note that we really want to limit any additional NuGet packages or external dependencies so please try to avoid adding any. Let me know if you have any questions.

**Comment by impworks** [comment]
@webprofusion-chrisc Alright, no NuGet packages are necessary here.

However, I'm not quite grasping the exception handling strategy for DNS providers. For example:
* `DnsProviderCloudfare.GetZones` returns an empty list, `DnsProviderDnsMadeEasy.GetZones` throws an exception
* `DnsProviderCloudfare.CreateRecord`:  catches all exceptions internally, `DnsProviderCloudfare.DeleteRecord`: does not catch anything

Is there any particular rule to adhere?

**Comment by webprofusion-chrisc** [comment]
@impworks thanks, hmm good question! Generally if a method returns an ActionResult then any internal errors should be caught and interpreted as a message back to the user. This will usually either be a permission issue or a comms problem. GetZones returning an empty list is because the UI can only show a list or an empty list, it doesn't currently have a way to handle a failure for that, because ultimately these exceptions happen in the background service and the UI is only expecting a list passed back from the internal service API,
