### ISSUE TITLE
Testing a PowerShell Post-request script without requesting a new certificate

### ISSUE THREAD

**Issue by swinster** [webprofusion/certify#379]
Many post request scripts will refer values of properties in the returned `$result" parameter. Testing these scripts without requesting a certificate results in errors/failures as there are nothing assigned to the parameter. 

Would it be possible to assign dummy values to the `$result` parameter on order that you can test the script fully, without requesting a certificate (which itf done to many time will cause a temporary ban). This would need to go through the motions of requesting a certificate but return something that is is simply a dummy cert, but would then allow you to see if the script functions as as intended.

**Comment by webprofusion-chrisc** [comment]
I think the most useful version of this would be to get you to request the certificate first before enabling 'Test', then 'Test' would just call the scripting using the successful values from your last request. The problem with a dummy cert is that most people are testing in their production environment(!) so we need to actively help them get a working result rather than potentially applying a dummy cert to a real service.  Maybe we could have a dropdown button that's 'Test with Dummy Results' or similar so that you're explicitly expecting it to give fake results.

As an aside, If the users pick an existing example script we also need to copy that script and store it somewhere, rather than using the example copy, as it's not clear that most examples need some degree of customisation and if we upgrade/change those scripts in future releases we don't want to suddenly break working renewals.

**Comment by webprofusion-chrisc** [comment]
This is now implemented as the Powershell deployment task in v5. Scripts can be run repeatedly using the UI and will run as the intended user (local service, local user or windows users) depending on the task configuration. You can now also check the 'Skip Certificate Request' checkbox (Certificate > Advanced) to test pre and post request tasks as a batch against an already acquired certificate. Note that at least one completed certificate request will always be required in order to have a properly populated results object (Certificate paths, thumbprints etc).
