### ISSUE TITLE
Setting to disable non-wildcard suggestion?

### ISSUE THREAD

**Issue by lollett** [webprofusion/certify#393]
Can we have a setting to turn off suggesting "Would you like to add the non-wildcard version as well?" when adding a wildcard domain?

**Comment by webprofusion-chrisc** [comment]
I'm guessing you might be using Manual DNS and that's why you'd like to switch this off? In general (from the beat testing feedback earlier in the year) users are trying to cover the domain and it's wildcard. 

For those using automated DNS Api's the requirement to update the TXT record with two values isn't usually a big deal but for manual DNS users it can be problematic and confusing.

**Comment by lollett** [comment]
I'm actually using automatic DNS API. Its just every time I create a "new certificate" with a wildcard it suggests "Add non-wildcard equivalent domain?"

It doesn't do this when creating standard certificates i.e. www.example.com so was suggesting a settings\checkbox to maybe disable the message box.

**Comment by webprofusion-chrisc** [comment]
Closing as won't fix. 

As the suggestion is a question (not a mandatory selection) and is applicable to all DNS users (even if manual DNS is harder to use) I'll keep it for now.
