### ISSUE TITLE
Exchange 2013 Cerificate Renewal

### ISSUE THREAD

**Issue by maxpaynejeju** [webprofusion/certify#424]
We have an upcoming coming renewal for certificate for Exchange 2013. 
This would be our first time to try Letsencrypt. 

I found two relevant threads for exchange:
https://github.com/webprofusion/certify/issues/303 
https://github.com/webprofusion/certify/issues/267

So do I have to run the following script in Advanced Option -> Scripting :
param($result)
set-alias ps64 "$env:windir\sysnative\WindowsPowerShell\v1.0\powershell.exe"
ps64 -args $result -command {
$result = $args[0]
write-output "Powershell Script Erfolgreich?" $result.IsSuccess
Add-PSSnapin Exchange
Enable-ExchangeCertificate -Server "Server01" -Thumbprint $result.ManagedItem.CertificateThumbprintHash -Services "SMTP, IMAP, POP, IIS" –Force
}

Or should I edit the "\CertifyTheWeb\scripts\common\MSExchangeEnableServices.ps1" file to include the above code?

Also would like to understand if I should select "(No IIS Website Selected)" or "Default Web Site" or "Exchange Back End" under Select Website ?

And don't I have to specify the CSR from Exchange server ?

**Comment by webprofusion-chrisc** [comment]
@maxpaynejeju sorry I'm not an expert in Exchange but in general yes this is correct. The process is in two stages:

1. Acquire the certificate (using http or DNS validation challenges to prove domain control)
2. Deploy the certificate (optionally to a single website, all applicable websites or use custom scripting to deploy to other services)

I would recommend copying the MSExchangeEnableServices.ps1 to a different folder (as it will be refreshed when updating the app otherwise) and editing it to your requirements. Using Certify v4 onwards there is no need to invoke the ps64 runtime as powershell will run as 64-bit by default.

I would start by acquiring a certificate, then refine your script for deploying the new certificate to the services you require.

Regarding a CSR: this is handled by the app when requesting the certificate, so no you don't have to generate one.

In the future we would like to add UI specifically for deployment to common windows services like Exchange, Remote Desktop Gateway etc.

**Comment by maxpaynejeju** [comment]
@webprofusion-chrisc Thank you for the information. 

So updated script would be:
$result -command {
$result = $args[0]
write-output "Powershell Script Erfolgreich?" $result.IsSuccess
Add-PSSnapin Exchange
Enable-ExchangeCertificate -Server "Server01" -Thumbprint $result.ManagedItem.CertificateThumbprintHash -Services "SMTP, IMAP, POP, IIS" –Force
}

I am doing for all services as that is what our current certificate is being used for. 

Also just wondering, do we have to first remove the existing certificate or automatically the letsencrypt certificate would be the active one?
