### ISSUE TITLE
Managed domains missing from list

### ISSUE THREAD

**Issue by kd8ssq** [webprofusion/certify#429]
I've been getting a lot of emails over the last few days about certificates from Let's Encrypt expiring within 30 days.  When I go to look at the UI to figure out why, the domains don't show up in the list.  Looks like this has happened for a few dozen domains.  The certs were originally created, but the domain doesn't exist in the list anymore.  After I re-added the certs, we have around 200 certs in the UI.

I'm assuming I was on some version of 4 back when the certs were originally added (sometime in November), but 2 days ago I upgraded to 4.1.3.

I can go back through the logs and see when the original certs were created, and I don't see any errors specific to any of the domains.

We have 5 different web servers all running Certify, but this problem currently has only been reported for 1 of the servers.

Also, it seems to be the same issue as #220

**Comment by webprofusion-chrisc** [comment]
Hi @kd8ssq this is not a known bug and is definitely not the same as #220 because that was back when we stored config as a json file, since 3.x it's been an sqlite db. The reason we switched to a transactional database was that users with many items were getting problems saving large collections to disk.

 I think it's would be useful if you could email support at certifytheweb.com with the following:
- a  zip of your c:\programdata\certify\manageditems.db file
- all of the relevant logs (your whole c:\programdata\certify\logs folder might be required)

If you have a backup of your server you can refer to it would be great to compare your c:\programdata\certify\manageditems.db from before november and after.  If there is manageditems.json.bak it would be useful as well.

There are only two opportunities I'm aware of for managed certificates to be deleted from the list:
- manually choosing to delete in the UI
- when the app starts and manageditems.db does not exist but an old manageditems.json does exist we import the manageditems.json items into a new database

The relevant source code is here: https://github.com/webprofusion/certify/blob/development/src/Certify.Core/Management/ItemManager.cs

p.s. I'd upgrade to 4.1.4 if you are using any DNS challenges anywhere, otherwise you may get renewal failures depending on your OS.

**Comment by kd8ssq** [comment]
Thanks Chris.

I'll get that email sent over.

**Comment by webprofusion-chrisc** [comment]
Closing -  support ticket.
