### ISSUE TITLE
Configure Auto Renew button not showing and no scheduled task created

### ISSUE THREAD

**Issue by rpruden** [webprofusion/certify#436]
In the latest version of version of 4.1.4.0 I am noticing a strange behavior. For upgraded instances, the scheduled tasks remains in tact and the button to Configure Auto Renew is still visible from the settings screen.

If I perform a fresh install on a server which has NOT had any version of the CertifyTheWeb client before, then I am not seeing the Configure Auto Renew button and there is also no scheduled task created that I can see which should be performing the auto renew.

**Comment by webprofusion-chrisc** [comment]
Hi, using the scheduled task to invoke renewal was deprecated in 3.x and is now kept only as a legacy setting in 4.1.x in favor of the default Background Service behavior. Since 3.x the renewals have all happened through the background service - using the scheduled task just asked the background service to run a renew-all

Certificate renewal using just the scheduled task has the disadvantage of not being able to dynamically cope with renewal failures (the background service has an exponential back-off for retry attempts).

If you need certificate updates to happen at a scheduled time for a particular service, you can choose' Certificate Store Only' as the Deployment Mode then script your own deployment to take the latest certificate and bind it as required.

I have added having a command line option to deploy (or re-deploy) a specific certificate to the to-do list #437
