### ISSUE TITLE
Webhook shows wrong ChallengeType

### ISSUE THREAD

**Issue by BergischNRW** [webprofusion/certify#438]
When I try to use webhooks for a notification and use the variable `$ChallengeType`, it will show `http-01`. Even though the Authentication is set to `dns-01`.

**Comment by webprofusion-chrisc** [comment]
Thanks, this behaviour is happening because when the feature was originally created a managed cert could only have one challenge type, now they have multiple but the old 'ChallengeType' field is still present in the model and defaulted to HTTP. 

Unless you need the $ChallengeType I would remove it or ignore it. I might not be able to remove it from the default payload as someone somewhere might be relying on that field being present.
