### ISSUE TITLE
Add Dnspod DNS support

### ISSUE THREAD

**Issue by lunzima** [webprofusion/certify#443]
Is it possible to add support for Dnspod as a DNS Provider?
Here's reference for many DNS providers:
https://github.com/Neilpang/acme.sh/tree/master/dnsapi

**Comment by webprofusion-chrisc** [comment]
@lunzima  thanks, I'm relying on the community to contribute code for the DNS APIs that they need as I often don't have access to the DNS providers to test and there are hundreds of APIs to choose from. I also have a fairly long list of changes to make in other areas of the app.

If you can contribute code for a provider that would be great, otherwise if you have an urgent need to get DNS validation working you can also try out the 'acme dns' API option for CNAME redirection.

**Comment by webprofusion-chrisc** [comment]
You can also use the DNS Scripting option to create your own create/delete scripts, sometimes that's a lot easier/quicker than implementing a DNS API provider.

**Comment by webprofusion-chrisc** [comment]
A DNSPod provider is coming in v5 courtesy of Posh-ACME : https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins

**Comment by webprofusion-chrisc** [comment]
Now implemented in v5 beta.
