### ISSUE TITLE
Issue with wirldcard Certificate

### ISSUE THREAD

**Issue by maxpaynejeju** [webprofusion/certify#444]
I tried to use the certify tool to generate wildcard SSL. I choose Manual DNS Entry, created "_acme-challenge.{mydomain}" TXT entry on DNS with the value shown on tool. However even after 12hrs it's still not working. When I used win-acme tool, it works instantly. 

![image](https://user-images.githubusercontent.com/46909224/53693553-643c7680-3de5-11e9-898f-b18f78e23abc.png)

![image](https://user-images.githubusercontent.com/46909224/53693557-70c0cf00-3de5-11e9-8146-e5482238358a.png)

**Comment by webprofusion-chrisc** [comment]
You went back to the UI and clicked 'Request Certificate' again? That's how you get it to resume the request.

**Comment by maxpaynejeju** [comment]
I tried it 4-5times. Each time the same response on Tool UI and the mail it
sent.

**Comment by webprofusion-chrisc** [comment]
@maxpaynejeju I think something is being confusing, the process should be : Create Certifcate > <configure requests as Manual DNS> > Request Certificate. 

UI/Email should tell you to create a TXT record.  The request will be paused while it waits. 

You then create/update the TXT record, wait for DNS to propagate to all your nameservers (can take an hour) and click Request Certificate again, this resumes the validation check and gives you a pass or fail depending on whether Let's Encrypt found the TXT record.

I recommend not mixing wildcard (*.domain.com) with domain certs (domain.com) as this can be confusing for manual validation because your TXT record has to hold two values.

Another alternative is to try out the acme-dns option, I find that's much easier than Manual DNS (it will ask you to create a CNAME with a specific value, from then on renewals use that).

**Comment by maxpaynejeju** [comment]
[log_cf0242c3-4f27-484c-aa70-4476b06db4a5_.txt](https://github.com/webprofusion/certify/files/2924299/log_cf0242c3-4f27-484c-aa70-4476b06db4a5_.txt)

I have performed exact same steps. Created the requested TXT record and then clicked on Request Certificate. Have tried multiple times to run Request Certificate. Have attached a portion of the log file.

**Comment by webprofusion-chrisc** [comment]
Hmm, can you try updating your contact email under Settings? It can be same address. This updates your account key internally. Just as an experiment.

Also I see that the log says Preview Mode, that usually indicates a test. I assume you're not completing the process by clicking Test.
