### ISSUE TITLE
Feature: HPKP Header Auto-Update

### ISSUE THREAD

**Issue by mattfinch** [webprofusion/certify#458]
Using certifytheweb is a pain for sites that implement the HPKP header, as the header needs to be updated each time the certificate is renewed. If it isn't the new certificate doesn't match the header and it causes problems.

Could the HPKP header be optionally set/updated whenever a new certificate is installed?

**Comment by webprofusion-chrisc** [comment]
Hi, I haven't tried that setup myself but yes it can be set on renewal using scripting.

Check Show Advanced Options and look at adding a post-request powershell script under Scripting. See https://docs.certifytheweb.com/docs/script-hooks.html 

You can then basically do anything you like with the certificate (things like the cert path and the thumbprint hash are provided in the results object for your script to use). I'm guess you'd be updating you websites web.config to set the header.

I don't think I'd want to add direct support for this in Certify The Web currently because we try not to modify the user's web.config (in fact we don't modify it at all) and I believe HPKP is in the process of being deprecated in favour of Expect-CT https://www.ryadel.com/en/expect-ct-http-header-security-chrome/

**Comment by wioxjk** [comment]
It could be solved by just keeping the private key intact.

https://github.com/webprofusion/certify/issues/478
