### ISSUE TITLE
Vault initialized using ACMESharp before IsAcmeSharpModuleInstalled method runs

### ISSUE THREAD

**Issue by ndouthit** [webprofusion/certify#46]
In MainForm.MainForm_Shown VaultManager is instantiated before the PowershellManager.IsAcmeSharpModuleInstalled runs. The VaultManager constructor initializes the vault with a call to the ACMESharp script Initialize-ACMEVault. This will cause an issue if ACMESharp isn't installed. IsAcmeSharpModuleInstalled should be called before the vault is initialized. The problem with that is that PowershellManager is a member of VaultManager. You could call IsAcmeSharpModuleInstalled in the VaultManager constructor but you wouldn't be able to pop up a message box explaining that ACMESharp is missing.

**Comment by soundshed** [comment]
Currently undecided if we should just bundle our own ACMESharp distro.

**Comment by ndouthit** [comment]
Might not be a bad idea. That way you'd be able to guarantee the right ACMESharp version is installed. I guess one downside is having to manage how you bundle the distro.

**Comment by soundshed** [comment]
I haven't investigated it yet but also I don't know what conflict handling we'd need to account for if we have our version of the module and the user also has the ACMESharp module installed. There is a clear argument for using ACMESharp directly rather than the Powershell commands but that does mean re-implementing a lot of stuff that's in the ps command-level code (or a lot of re-org for ACMESharp)

**Comment by soundshed** [comment]
ACMESharp module loading step removed, we now load our own bundle of ACMESharp instead of the PowershellGallery version.
