### ISSUE TITLE
Certify the web API to Power DNS

### ISSUE THREAD

**Issue by Sepehrsystems** [webprofusion/certify#462]
Hello
Can Certify the web automatically add dns records (like text record) to Power DNS?
for example we use Power DNS API and connect certify the web for adding Text records automatically..

**Comment by webprofusion-chrisc** [comment]
Hi, there is no current support for PowerDNS. We would accept a user contributed provider (there are other examples to copy) but it's not currently planned otherwise.

You can use the DNS scripting option to use a custom batch file to create/delete the txt records instead, in which case you would likely call the API using either curl or PowerShell.

**Comment by webprofusion-chrisc** [comment]
New DNS providers are added by submitting scripts to the Posh-ACME project. In general we will not be adding more DNS providers (as C#) but we will accept them via Posh-ACME: https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins

**Comment by marcovanbeek** [comment]
Hi, Support for PowerDNS has been in PoshACME for at least 2 years but isn't in the dropdown of scripts yet in CertifyTheWeb. I also note that the entry for doing it via RFC2136 using nsupdate is no longer a valid method, as nsupdate for Windows is no longer available from the ISC. I am currently working on a script so that I can renew a certicate via the custom script method, but I don't know enough about what CertifyTheWeb needs for this to get added as an option.

**Comment by webprofusion-chrisc** [comment]
@marcovanbeek thanks for reminding me, yes I think we can probably enable this soon. There have been a few other providers added to posh-acme we may be able to integrate, some have special conditions etc that aren't really appropriate but standard ones are fairly easy to add.

Regarding nsupdate,if the source is available somewhere we could probably bundle our own exe, if not then it's pretty much obsolete.

**Comment by webprofusion-chrisc** [comment]
@marcovanbeek on the topic of nsupdate releases, it looks to me like you can just grab the latest build from their public repository: https://gitlab.isc.org/isc-projects/bind9/-/artifacts

**Comment by marcovanbeek** [comment]
@webprofusion-chrisc re nsupdate, I had a look at that link, and it looks that they have been slowly phasing out the Windows version of Bind for a few years, based on this page: https://kb.isc.org/docs/supported-platforms so Bind 9.11 works on all Windows Platforms but went EOL in January 2022, Bind 9.16 supports Windows 10, & Server 2012R2, 2016 and 2019, and just went EOL this January, (although it looks like Server 2019 support will be community maintained until September 2024) and Bind 9.18 has no support for Windows whatsoever.

**Comment by webprofusion-chrisc** [comment]
PowerDNS has now been implemented in v6.0.15
