### ISSUE TITLE
Install cert on remote server

### ISSUE THREAD

**Issue by tomchadwin** [webprofusion/certify#477]
I guess this is a very basic question. We have an Exchange cluster. I therefore need to install the LE cert not only onto the local box but onto a second box at the same time. How can I script that?

**Comment by webprofusion-chrisc** [comment]
Hi Tom,

I'd maybe also try this question on https://community.certifytheweb.com to see if anyone has a better answer, but the answer is: it's complicated. 

It mostly depends on how you are doing domain validation (if using http validation and your load balanced DNS is round-robin then potentially the Let's Encrypt http validation request will be checking the server that's not running Certify. Once you have your certificate you can then script the copy/install/deployment to the other server. There are plans to help with the scenario in future release but it's not currently a feature.

If you are using/can use DNS validation (using a DNS API, even if you have to use the scripting option to do the DNS updates yourself) then it's much easier as both servers can just manage their own certificates independently as if the other server didn't exist, so that;s what I'd do.

**Comment by tomchadwin** [comment]
Thanks for the reply, Chris. I've got validation working as you suggested - Certify box validates, and DFS syncs the validation folder over to the other box, so whichever box DNS resolves to has the response file.

So I've got the cert successfully, it's installed, and the Exchange 2016 script is assigning it to the right Exchange services. However, it's only installed and assigned on the Certify box, not the other one. I've seen [this question](https://stackoverflow.com/questions/28899377/install-a-pfx-certificate-on-a-remote-server-with-powershell) which suggests that I use `Invoke-command` to install the cert on the remote box. However, the command invoked requires the cert password, and I couldn't see that listed as a variable on the [scripting hooks](https://docs.certifytheweb.com/docs/script-hooks.html) page.

**Comment by webprofusion-chrisc** [comment]
Sounds like you're nearly there. The default password is blank, so that may be "".

**Comment by tomchadwin** [comment]
Ah! Never thought. Let me try and report back. Thanks!

**Comment by tomchadwin** [comment]
I think this is now working. I was trying to set the password as "", but `ConvertTo-SecureString` fails with a zero-length string. I removed the whole `-password` parameter, and it seems to have worked. Thanks for the help!

**Comment by tomchadwin** [comment]
I ignored the warnings in the example scripts, and edited one in place, so it got overwritten by an upgrade. Managed to rewrite it, so though I'd better put it here, if not for others' use, then probably for my own in the future:

```
Copy-Item -Path $result.ManagedItem.CertificatePath -Destination "\\PATH\TO\SHARE\temp.pfx"

# enable powershell snap-in for Exchange 2010 upwards
Add-PSSnapIn Microsoft.Exchange.Management.PowerShell.E2010

Invoke-command -ComputerName REMOTE_MACHINE_NAME -scriptblock { 
    Get-Command -Module PKIClient; 
    Import-PfxCertificate –FilePath C:\LOCAL\PATH\TO\SHARE\tmp.pfx cert:\localMachine\my 
}

Enable-ExchangeCertificate -Thumbprint $result.ManagedItem.CertificateThumbprintHash -Server REMOTE_MACHINE_NAME -Services POP,IMAP,SMTP,IIS -Force
```
