### ISSUE TITLE
Client Certificate Mapping to AD failing after Certificate Renewal

### ISSUE THREAD

**Issue by hirsh2020** [webprofusion/certify#486]
We have a site that uses SSL client certificates for authentication to backend AD accounts. Whenever Certify runs and updates the LE certificate all looks normal except that when authenticating the accounts prompt for basic auth type username and password prompt. The work around is to bind the site to different SSL certificate and restart then rebind to the new LE certificate and restart. After this authentication returns to normal. Any ideas?

**Comment by webprofusion-chrisc** [comment]
Hi, sorry no idea what that problem would be unfortunately - I have no relevant experience with Client Certificates. 

Seems like an issue in either the client or the server or it's somehow pins the serial or public key of the server Tls certificate and invalidates previous authentication when that changes. I think you'd be best to escalate this to the relevant vendors for the client or server components. A lot of older software doesn't expect the server private key to change regularly or expects the CSR used to request the SSL certificate to stay the same etc, and that's just not the case any more (we don't re-use private keys currently in CTW).

**Comment by hirsh2020** [comment]
It seems to be something with the way the LE certificate is bound to the IIS sites, because using the GUI to just do a bind to a different cert (even a previous LE cert) then binding again corrects the issue. However just restarting the service does not.

**Comment by webprofusion-chrisc** [comment]
There is an checkbox 'Show Advanced Options' in the app when you click on a managed certificate, this enabled a new tab called Other Options, from there there is a Re-Apply Certificate to Bindings button - you could try hitting that instead of manually editing the binding just to see it makes a difference. Behind the scenes that re-imports the certificate into the computer certificate store and sets the certificate thumbprint on the binding (again). If that works it suggests a problem with private key access.
