### ISSUE TITLE
Cannot install certificate via https only

### ISSUE THREAD

**Issue by matthiasg** [webprofusion/certify#502]
With pure letsencrypt is is possible to verify a certificate even if the website is currently hosted behind HTTPS only (even if the certificate is not trusted). That enable to disable all HTTP access to a site and get started via HTTPS only, then switch to the LetsEncrypt cert.

Is this somehow possible in certify ?

**Comment by webprofusion-chrisc** [comment]
Hi, we used to support tls-sni-01 but that was deprecated by Let's Encrypt a few years ago, we haven't yet implement tls-alpn-01 because there hasn't been any demand until now (hi!) and at the time there were some limitations regarding the .net framework we use. 

Coupled with the move to ACME V2 and the increased use of DNS validation (creating/updating a TXT record in your domain's DNS, or using an acme-dns server to delegate via a CNAME record) tls-alpn-01 hasn't been required. Happy to use this as a tracking issue for eventual support though, if it's tls-alpn-01 you're after.

**Comment by matthiasg** [comment]
Thanks for the specific feedback, very much appreciated. Too bad though. The kind of servers we want to open don't have managed DNS for automatic DNS validation and I would rather have no HTTP Port open at all. I will have to invest some time validating the HTTPs server parts and what data it can access then.

**Comment by webprofusion-chrisc** [comment]
You could use v5 (currently in beta) and add a Pre-Request deployment task to open port 80 in the fireall, then a post-request Deployment Task to close it again if you like, then http validation would proceed as normal (there is no need for IIS http bindings on port 80, certify has it's own temporary http challenge server). v5 deployment tasks can also be used to perform certificate renewal from a central server (DNS validation usually) then distribute certificates to other machines, depending on your requirements.

**Comment by matthiasg** [comment]
I will check out the built-in webserver then. Thanks
