### ISSUE TITLE
Does this detect running instances of .net core apps not in IIS itself but running with kestrel?

### ISSUE THREAD

**Issue by AraHaan** [webprofusion/certify#504]
I would like to know if this works well with kestrel when not using IIS directly.

**Comment by webprofusion-chrisc** [comment]
Hi,

The app can be used to acquire certificates for use directly with Kestrel or any other web server. It does not currently do any dynamic configuration for kestrel, so you would have to configure Kestrel yourself to point to a certificate (which Certify can renew as required). After each renewal you would need to signal kestrel to use the latest cert (if it doesn't do so by itself), probably by restarting your service.

There are other popular Let's Encrypt middleware tools such as : https://github.com/natemcmaster/LettuceEncrypt but these tend not to be able to use many forms of DNS validation etc.

There are plans forming currently to integrate certify as a certificate server (API) to kestrel middleware (so that kestrel doesn't need to acquire it's own certs, instead fetching pre-prepared certs from the certify server). This would also help with load balancing or continuous deployment scenarios.

**Comment by AraHaan** [comment]
I would like having that sort of middleware. Although it would also be nice to have it where one did not have to restart the service just for it to use the latest cert as well (have it automatically use it).

And then just install it like ``app.AddAutoRenewingSSL()`` or something in my code and basically forget.

I also been trying to figure out how to also log exceptions throw in fire-and-forget on some parts of my service. It is also sad though that for some reason I cannot use the memory profiler on it to ensure it has no leaks though. I am just hopeing it does not have any as well.

So basically the certs are saved to a file somewhere right in the application?

Also another question: It says there are limited number of certs these does not include renewals right? Just hoping as well I technically do not have a server, I basically just went into my router, froze my static IP, set kestrel to use my static IP instead of localhost and specific ports (5000, 5001), then went into the router and have it have external ports 80 map to 5000, and port 443 to 5001, and then that public IP DNS'd to my free domain. So for me the 3 server option would seem like a waste.

So for me I think there should be a cheaper option added where it would only include 1 if it applies to renews as well.

**Comment by webprofusion-chrisc** [comment]
If you are using v5 (beta) there are new Certificate Export options for certificate deployment tasks (under Deployment) so you can export the certificate to wherever you need it (locally or on a remote server) as any file type you need. v4.x required custom scripting to achieve the same things so I'd use v5.

Regarding licenses - the free Community Edition will manage up to 10 certificates, each certificate can cover one or more domains. It has unlimited renewals and up to 100 domains per certificate, so that gives you support for up to 1000 domains in the free version. Subject to the limits of Let's Encrypt or the Certificate Authority you are using.  v5 also supports BuyPass Go ssl (180 day certs, single domain). You should look at DNS authorization instead of http, that will save messing with firewalls and any machine can do the renewals etc.

**Comment by webprofusion-chrisc** [comment]
See also: https://certifytheweb.com/home/features

**Comment by AraHaan** [comment]
Hmm it seems freenom dns api's is missing from dns api options. And yes the domain I use is from freenom.

Edit: Looks like it could possibly be added https://github.com/dabendan2/freenom-dns

**Comment by webprofusion-chrisc** [comment]
Yes, there are actually thousands of possible DNS apis and it's not possible to provide them all, instead we provide the most popular ones and extra ones are added via PoshACME  (they accept patches!): https://github.com/rmbolger/Posh-ACME/tree/master/Posh-ACME/DnsPlugins

For those we don't support you can use the DNS scripting option to script your own create/delete of TXT records, or you can use acme-dns, or switch to a supported provider (such as Cloudflare which is free).
