### ISSUE TITLE
Use own CSR to get certificate

### ISSUE THREAD

**Issue by uxkjaer** [webprofusion/certify#509]
Hi,

First of all awesome tool. I've tried to use this to sign a self signed certificate of an SAP ABAP Netweaver trial system. The problem here is the certificate is generated by the SAP system and I get a CSR to sign. So I can't use the tool to upload that.
I've used zerossl.com in the past, but they now require payment to get a certificate and I was hoping this extension would be something you could include.
If so then you would make a lot of developers in the SAP ecosystem happy.

**Comment by webprofusion-chrisc** [comment]
HI Jakob, yes that's been on the list of things to include for a long time but it's not currently supported. 

Do you have to upload the resulting certificate to the SAP portal UI or is there any API you could use? 

Do you have to generate a new CSR for every renewal or do you re-use the same one?

What format is the certificate you upload to SAP (.pem/crt, .pfx)

**Comment by webprofusion-chrisc** [comment]
As an aside, if you select BuyPass Go as the certificate authority, instead of Let's Encrypt, your cert will last for 180 days, rather than 90, which may be useful if you have manual steps. Ideally we'd work out how to automate so that you don't have any manual renewal.

**Comment by webprofusion-chrisc** [comment]
I don't support you can point me to a download for a trial version of the product you're using? Ideally with general steps on getting it configured enough to try out the SSL config step.

**Comment by uxkjaer** [comment]
Hi, Thanks for your quick response. Sorry i've been so slow. 

Easiest is to use a docker container to spin up your abap system
https://blogs.sap.com/2019/12/11/running-sap-nw-7.52-sp4-trial-in-docker-in-windows-subsystem-for-linux-2/

Then follow something like this blog on how to create the certificate
https://blogs.sap.com/2016/07/23/enabling-on-premise-fiori-sso-with-openssl-certificates-part-1/

your default user is 
username: developer
password: Down1oad

You can access the GUI from path https://localhost:44300/sap/bc/gui/sap/its/webgui

**Comment by webprofusion-chrisc** [comment]
Thanks! It looks like it needs a few hours and many GB to get that up and running, so maybe not today! Shame they don't offer a prebuilt VM. Keen to make sure we are compatible though.

**Comment by uxkjaer** [comment]
I'm happy for you to share my system if you want?

**Comment by webprofusion-chrisc** [comment]
@kovboyjder thanks, I've downloaded 9 out of the 11 parts so I'm nearly there. I'll see how I get on and get back to you once I've tried it out.

**Comment by uxkjaer** [comment]
It's shot notice. But I'm working out of Australia and would be happy to support you with the sap stuff. It's not easy for an outsider to do it all. I'll be on my computer about 12.30 cest most days. Let me know if you need a hand. If you are in a similar timezone let me know and I'll be happy to help you during working hours.

**Comment by webprofusion-chrisc** [comment]
Thanks, it's interesting to try it out because there are probably other sap related services which require certificates. I had a play with the SAP Cloud Appliance Library on AWS but hit a config issue so I may try that again. Currently running the docker/WSL2 version of the instructions and it appears to be installing OK, if I don't run out of disk space :)

Meanwhile, could you possibly supply a sample CSR file via support {at} certifytheweb.com? Can you confirm the output certificate format the SAP requires (e.g. a PFX or other container, or component files like .crt/pem) - just whatever types you were feeding it from zerossl before maybe? Do you do any conversion before upload?

**Comment by webprofusion-chrisc** [comment]
Thanks, got those files. Is there an easy way to change the fully qualifed name for the system? My one in docker seems to be *.dummy.nodomain and try really try it out with Let;s Encrypt I'd need to change it to one of my real domains. Failing that I can use a custom CA if changing that is quite complicated.

**Comment by uxkjaer** [comment]
Hi Christopher

I've recorded a little video on how to do it.

https://drive.google.com/file/d/1cUOCbcU4ZuTiqC-RiJX-hPm-0E5wLdLK/view

After you made the change, stop the system from your console using command
stopsap. Then start it again and the fqdn should be all good.

//Jakob

**Comment by webprofusion-chrisc** [comment]
Excellent, thanks! For some reason I am able to launch the desktop SAP GUI and connect, but accessing https://localhost:44300/sap/bc/gui/sap/its/webgui results in a page saying 403 forbidden, and my account can't access SAP support notes (presumably you pay for that). I'll try again with SAP Cloud Appliance library as that should be working out the box, the docker option was preferable because it doesn't cost anything.

I'll get you beta version to try out that accepts a custom CSR, there's just some UI work needed for that to make sense (if you are providing a CSR then you can't also specify domains manually etc) - it should be available early next week.

**Comment by webprofusion-chrisc** [comment]
Found this (old) article to get check webgui config: https://blogs.sap.com/2014/02/06/how-to-configure-your-sap-gui-html-for-web-access/ making some progress!

**Comment by uxkjaer** [comment]
If you can open the GUI via 8000. The go to transaction sicf.

Press f8 and add webgui to the filter and click apply.
Find it in the tree and right click and activate it.
Click the yes button with the icon on.

Now try again from Port 44300.

**Comment by webprofusion-chrisc** [comment]
Thanks! I got it all working then I killed it by changing one of the other hostname settings while experimenting. I'm used to just editing a config file and restarting the service :) - at least I'm learning!

**Comment by uxkjaer** [comment]
Haha yeah it's a brave new world and welcome to the world of enterprise
complexity. If you stuff up your profile parameters. You can revert to the
previous profile. They are stored in /sapmnt/NPL/profile or something like
that. The name is the same as you see in rz10 and the one without a suffix
is the active one. So change that to
.bak and rename one of the others
Then start your system again.

**Comment by webprofusion-chrisc** [comment]
@kovboyjder so I now have this working (cert requested using certify then applied manually using the standard STRUST UI), but there are some rough edges to work out.

My general process currently is:

- Replace the default PSE, set just CN=<domain>, add any other names you want to include in the cert:
![image](https://user-images.githubusercontent.com/2445502/86897281-c9bb1880-c139-11ea-8174-4d8a09245bca.png)

- In certify, create a new managed cert, add the same domains (set the CN=<domain> domain as Primary so that it's included as the subject). Set the CSR to use (UI in progress, this may auto populate the domains)

- Use DNS Validation (under Authorization), I recommend either using acme-dns (CNAME redirection) or another supported DNS API rather than using the manual DNS option (that's a last resort).

- Under Deployment, set Deployment mode to None (there is probably no need for deployment to IIS etc)
- In the Deployment Tasks tab, add a Certificate Export task, set to export full chain.
![image](https://user-images.githubusercontent.com/2445502/86898068-cbd1a700-c13a-11ea-8c43-46d8cc891658.png)

- Request the certificate

- Once completed OK, use the Import Certificate Response button in STRUST to import the pem output from the above deployment task.
- Done!

I think renewals would be:
- Request certificate (which will happen automatically normally, so can just use latest)
- repeat import certificate response in STRUST

**Comment by webprofusion-chrisc** [comment]
If anyone knows a way to import the certificate response via an API, that would completely automate renewals.

[edit: if you can figure out how to use sapgenpse to import the latest certificate pem, that would automate renewal, assuming that would also notify sap ICM of the cert update]

**Comment by uxkjaer** [comment]
Hi Christopher, 

This is awesome!

I'm not really that into .net. Is there a way for me to build the project and test it myself?

I'm using GoDaddy as my DNS provider their API does have ability to fetch the CSR it seems.

https://developer.godaddy.com/doc/endpoint/certificates#/v2/getCertificateDetailByCertIdentifier

And also to post it.
https://developer.godaddy.com/doc/endpoint/certificates#/v1/certificate_create

I have tried it with another tool, but not where I could do the CSR.

//Jakob

**Comment by webprofusion-chrisc** [comment]
Thanks Jakob, I'll get a beta version out as soon as possible for you to try, building the app yourself and getting it running would be a bit time consuming for you.

Regarding GoDaddy, the CSR stuff they do is for when you want to buy certificate from them, so it's unrelated to their DNS API. 

Using the current version of Certify you would be able to create a certificate as follows (feel free to try it if you haven't already):

- create a new managed certificate, add your domain
- set your DNS Authorization to GoDaddy, set the API credentials (and choose the DNS Zone)
- then hit Request Certificate. 

That would then fetch you a certificate for your domain from Let's Encrypt (with DNS validation against Go Daddy) but you wouldn't be able to easily import it into STRUST - because the private key and potentially the signing algorithm used in the certificate signing request is different. I was also investigating exporting the SAP private key then importing that into Certify but SAP didn't like the result, so there is some disparity with that approach.

**Comment by webprofusion-chrisc** [comment]
Hi Jajok,

Here is a test (alpha) version:
https://certifytheweb.s3.us-east-1.amazonaws.com/downloads/test/CertifyTheWebSetup_V5.1.0_alpha.exe

When you create/edit a managed certificate you can choose your custom CSR under the Cerificate > Advanced tab. This then auto populates the domains etc for the certificate request. You can then request your certificate as normal:
- Deployment mode can be set to auto or none etc.
- Add a `Certificate Export`  Deployment Task and set it to export as PEM - Full certificate chain (as above).

When the request/renews runs (or any time you click run on the certificate export deployment task) the PEM file will be exported to the path you specified, you then import that into STRUST as your certificate response.

**Comment by webprofusion-chrisc** [comment]
If that works you should also try out using BuyPass Go as the cert authority, because then you get 180 days instead of 90, I haven't tried it in SAP though.

**Comment by uxkjaer** [comment]
This is awesome!

I've tested both the buypass and let;'s encrypt. Both works flawlessly.
Awesome work!

I'll write a blog and as soon as you publish the changes ill put it up.

Thanks again!
Kind regards
Jakob Marius Kjær
PHone: (+61) 0413 980 556

Linkedin: http://dk.linkedin.com/in/jmkjaer
Twitter: https://twitter.com/uxkjaer

**Comment by webprofusion-chrisc** [comment]
Great! I'm glad that worked. I'll be out of town this week so I'd predict the beta will go out next week and the final 5.1.x release the week after.

**Comment by webprofusion-chrisc** [comment]
I forgot to mention this feature was deployed as part of 5.1.x so it's been available for a few weeks now.
