### ISSUE TITLE
$ChallengeType always shows http-01 even if dns-01 was used in validation when executing webhooks

### ISSUE THREAD

**Issue by areis422** [webprofusion/certify#525]
Example webhook posting to Teams channel:
Body:
```
{"@context": "https://schema.org/extensions","@type": "MessageCard","themeColor": "EE3224","title": "Certificate Renewal status for $PrimaryDomain","text": "**Success**: *$Success*\n\n**Primary Domain**: *$PrimaryDomain*\n\n**SANs**: *$SubjectAlternativeNames*\n\n**Challenge Type**: *$ChallengeType*"}
```

Example output in Teams channel:
```
Success: true
Primary Domain: sub.domain.tld
SANs: sub.domain.tld
Challenge Type: http-01
```

**Comment by areis422** [comment]
Specifically using Amazon Route53 API. Can confirm that certificates are actually issued using dns-01 since servers are not publicly accessible for http-01 to even be an option.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes this has been raised before, in older versions we only had one challenge type per managed certificate, now we support multiple, so a request could use multiple challenge types. We could set that to be just the first option used though which would mostly be correct.

**Comment by areis422** [comment]
In that case, is it possible to extend tasks to be able to choose a task or
tasks per configuration? Ex. If I've got 2 http and 1 dns in the same
certificate, be able to perform different tasks per configuration? Either
that, or change the "output" our add additional variables to be consumed by
tasks such as the webhook?

**Comment by webprofusion-chrisc** [comment]
Hmm, so you mean report to webhooks etc differently depending on which challenge type was attempted? I think that level of sophistication/customisation might be something we would leave as an exercise to the reader - I don't know is the answer. 

You can pass the Result to a PowerShell script then do what you like with the information (including posting to webhooks etc). There may still be things we need to add to the data model to help with that reporting but the reason we offer scripting is so users can basically do what they want with the info, rather than us trying to build every combination.

The main reason I'm reticent to devote much engineering in that direction is that things like webhooks only seem to get very light usage. According to application insights (the telemetry option under Settings) the webhook feature in 5.1.x got used 15 times in the last 30 days, in a sample size of 7.5M events. Our stats could be wrong/massively incomplete though as many people (presumably) opt to not send telemetry.

**Comment by webprofusion-chrisc** [comment]
Out of interest, regarding the webhook output that you send to teams, how does that then get used? Is it just a channel message or are you doing further reporting using that info?

**Comment by areis422** [comment]
I've got a channel with a webhook so I can monitor success or failure on
50+ servers, mostly Linux using certbot, but I now have a single one of
glass for letsencrypt certificates instead of waiting 6 hours for my zabbix
monitor to update with new expiration dates

**Comment by webprofusion-chrisc** [comment]
Thanks, so do you use the same webhook for certbot as well? We have a basic dashboard option as part of Certify but it is very basic and doesn't intergate with certbot currently. We'd like to offer a generic dashboard service/product if there was enough interest.

**Comment by areis422** [comment]
I have a shell script in the renewal-hooks/deploy folder that creates a
similar payload and uses curl to post it to the channel via the same webhook
