### ISSUE TITLE
v5.1.5.0 does not connect to service

### ISSUE THREAD

**Issue by BananaAcid** [webprofusion/certify#527]
It did work until I updated.

Just updated from 4.1.6.0, to 5.1.5.0 which did not work, then uninstalled, reinstalled - does not help. (After all that - re-installing 4.1.6.0 made it work again)

What did not work with 5.1.5.0:
The service is running, but the app gui does not show the config and closes with a dialog box showing "Certify SSL Manager not startet. ...".

The service is listet as running.

C:\ProgramData\Certify\logs\service.exceptions.log shows: `[9/8/2020 10:31:48 PM] :: Service API bound OK to http://localhost:9696`

`http://localhost:9696/api/system/appversion` shows `<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">5.1.5.0</string>`

Any advice?

edit: added version numbers to comment

**Comment by webprofusion-chrisc** [comment]
Hi, I don't recommend downgrading to 4.1.6 from 5.x as the configuration files have changed slightly. In 5.1.x there is a new servers.json file created which stores the list of servers that the UI knows about (usually only 1). Check that the port 9696 is also shown in this file and that matches serviceconfig.json. Eventually you will be able to use one UI to connect to one or more servers running Certify (windows or linux etc).

You can also just delete servers.json and serviceconfig.json and these files will be recreated when the service is restarted or app reinstalled.

**Comment by webprofusion-chrisc** [comment]
Did you ever get this working?

**Comment by BananaAcid** [comment]
I am still using the downgraded version. The only bug I have to cope with, is the tool not updating all SSL references in IIS.

**Comment by webprofusion-chrisc** [comment]
I'm not aware of any IIS binding bugs for v4.1.6 - does the Preview tab show you that it will update the correct bindings? Is there anything special about the bindings you are trying to update?

**Comment by BananaAcid** [comment]
One case I found, was having a subdomain in the bindings with a different certificate, that was used for a domain as well. domain updated but the cert on the subdomain on the other domain did not.

```
mailserver.com -> cert A
*.mailserver.com -> cert A

client,com -> cert B
*.client,com -> cert B
mail.client.com -> cert A --> did not update
```

**Comment by webprofusion-chrisc** [comment]
Interesting, I'm not sure I totally follow, Let's Encrypt won't let you have a single certificate for `*.client.com` and `subdomain.client.com` because the wildcard already covers the subdomain label. 

If you have a wildcard managed cert for a domain and it just uses the auto deployment then that will be used for whichever sites it can be applied to (e.g. *.client.com can be applied to mail.client.com). You could change the deployment mode to target it more though. The Preview tab will always explain the planned bindings updates though, so you can see if extra sites will be affected. By default IIS websites need to be started to get the cert applied, so if it's stopped for any reason it won't get the cert update (by default).

If you find a bug in the latest version please do report it.

Regarding getting the service to connect on the latest version, try changing 'localhost' to '127.0.0.1' in both the `serviceconfig.json` and `servers.json` files. If you can get it working on a snapshot/clone of your machine first that's the best way to try out different solutions.

**Comment by BananaAcid** [comment]
what I forgot to mention, cert A is setup to include these 3 domains/subdomains ... and the "change the cert on each binding where the old one is installed" (or however this was called) was enabled.
