### ISSUE TITLE
Feature Request: Run argument passing

### ISSUE THREAD

**Issue by WORMSS** [webprofusion/certify#537]
I know `Run...` is still an experiment and I understand that passing data to any command line function will be super difficult compared to how Powershell works, but I was wondering if it would be possible to have checkbox to store $result object a file location, and then passing that file location to a $results argument?

![image](https://user-images.githubusercontent.com/1384537/99464010-050ef480-292f-11eb-8f46-e33bce77f7bf.png)

Excuse the sloppy picture, I made it in paint..

**Comment by webprofusion-chrisc** [comment]
Thanks, sorry I missed this issue. Yes there is some hidden complexity there as your intended path may be on a remote file system etc. The simplest solution is to provide it powershell script task which writes out the result to a file, then calls your next script (using node or whatever you like):

```powershell
param($result)  

$logpath = "C:\Temp\Certify\Powershell\ps-result.json"
Add-Content $logpath ($result | ConvertTo-Json)

# then do something else, e.g. run a node script (may need to specify full path to node exe)
node C:\Scripts\process-certify-result.js
```

**Comment by WORMSS** [comment]
Damn, I didn't think of that at the time.. I can only blame tiredness. Lol

**Comment by WORMSS** [comment]
Side question.
Do you have a JSON Schema for the result argument?

**Comment by webprofusion-chrisc** [comment]
No sorry I don't, the main result content is the managed certificate settings info, which is here: https://github.com/webprofusion/certify/blob/development/src/Certify.Models/Config/ManagedCertificate.cs

Alternatively you could save a response and use a schema generation tool but that may miss some edge cases. You also need something that's not brittle if the app gets updated and the schema gets slightly changed (unlikely but possible, most stuff gets added rather than modified).
