### ISSUE TITLE
Packages missing when trying to build locally

### ISSUE THREAD

**Issue by ndouthit** [webprofusion/certify#55]
I had some trouble getting the source code to build locally on my machine. Building it restores the NuGet packages but for some reason they're still missing.

I had to uninstall/reinstall the NuGet packages below in order to get the project to compile.
- AWSSDK.Core
- AWSSDK.Route53
- AWSSDK.S3
- log4net
- Newtonsoft.Json
- BouncyCastle.Crypto

**Comment by soundshed** [comment]
Hi Nathan, thanks - the project now uses ACMESharp as a gitsubmodule (under src/lib/), so we can build and include the bits of ACMESharp we need. I found I need to run 'git submodule init' to get ACMESharp to include in the sync. The issue with nuget package restore is (I think) a limitation of the nuget/vs solution because we are including projects from a different solution.

**Comment by ndouthit** [comment]
Cool thanks. Just wanted to make sure I wasn't alone and/or doing something wrong.

**Comment by soundshed** [comment]
Further to this, the trick is to open the ACMESharp solution and do a build - to do that I had to Unload the '..'test..' projects from the solution. From then on the packages are restored when visual studio thinks they should be.
