### ISSUE TITLE
Results ChallegeType returns wrong

### ISSUE THREAD

**Issue by Supreme-Bob** [webprofusion/certify#568]
I'm using DNS challenge in the 5.5.2.0 version $results.manageditem.requestconfig.challengetype is retuning "http-01" instead of dns-01.

**Comment by webprofusion-chrisc** [comment]
Hi, the RequestConfig.ChallengeType value is deprecated since we started to offer multiple challenge configurations per managed certificate (so you can answer challenges differently depending on the domain you are trying to validate), it's only kept for compatibility with old scripts.

`ManagedItem.Request.Config.Challenges` is the real list of challenge configurations, each of which have a ChallengeType.
