### ISSUE TITLE
How to move the install from one PC to another

### ISSUE THREAD

**Issue by GRIFFCOMMca** [webprofusion/certify#571]
HI, we have a licensed copy running in Windows 7, we are migration the webserver to Windows 10, how do we backup all the settings then paste them in to the new install?  I cant seem to find a backup for the settings.

Many Thanks

**Comment by webprofusion-chrisc** [comment]
Hi, support requests should be emailed to `support at certifytheweb.com`. The short answer is that it depends on your versions and you may be able to use the migration import/export tool, but if you only have a few site it's easier to just set up the new server with new configuration. Please email support with more details about your current configuration.

**Comment by GRIFFCOMMca** [comment]
Hi, sent an email to the above address, received the below error:
  support at certifytheweb.com
    **all relevant MX records point to non-existent hosts or (invalidly) to IP addresses**

Please advise

**Comment by webprofusion-chrisc** [comment]
Thanks for raising that! we'll check that from here.

You can tell me more here if you want to, it's just harder to track than using our helpdesk ticketing.

Migration is not yet fully supported but it _can_ be done, so it depends what versions you are currently working with, how many sites you have etc.

**Comment by webprofusion-chrisc** [comment]
Regarding the MX record (when sending emails to support), that should be fixed now, your system didn't like our configuration which used an IP address, so we've updated that to point to an A record.

**Comment by GRIFFCOMMca** [comment]
I believe we have this working:
- v5.5.4.0
- Installed a new copy on the Windows
- Backup folder c:\programdata\certify
- Copy above folder to the new PC, stop the service then copy the backup folder over the current, restart service
- Run application, all certificates and settings are in the new program
- De-activate the current install, active the new one, tested working ok with an SSL, so i believe they all should work

**Comment by webprofusion-chrisc** [comment]
Yes, here is an outdated guide: https://community.certifytheweb.com/t/migrating-to-a-new-server/889

From v5.x onwards more things are encrypted using the windows data protection APIs, so moving a 4.x install to a new server could be easier than moving a 5.x install. In 5.x we added a (beta) migration tool which can be perform import and export of settings. This is enabled under Settings > UI Settings.

Ultimately if the approach you have landed on is working then it's all good. You will still need to add your certificates to IIS or re-apply them individually (you can use Certificate > Advanced > Actions > Re-apply Certificate to Bindings) but you should also review the Preview tab bindings section to ensure the expected binding updates will happen. Changes to IIS Site IDs between servers can affect bindings updates if the Single Site deployment option was used previously (instead of Auto).

You will need to test that renewals are working by renewing one of your certificates (using Request Certificate) and you should monitor renewals are working normally at least for the first renewal.

**Comment by GRIFFCOMMca** [comment]
We are on Apache, so the certs were copy / paste.  We did renew one cert and it went as expected, then checked the disk where the SSL are stored and its the correct date (today)... it appears to be ok, however i agree it should be monitored on renew.... however anything major goes wrong we can re-create that cert setup in the software.

**Comment by webprofusion-chrisc** [comment]
Great, sounds like you have it all covered!
