### ISSUE TITLE
Domain match rules won't save correctly

### ISSUE THREAD

**Issue by vitaprimo** [webprofusion/certify#586]
This isn't exactly new, recently I update the app and it surprised me that it was still there.

When using DNS validation (I use Cloudflare) for several domains, you'd select your zone ID then type the wildcard domain and the regular domain in the box, right? Select the next zone ID, repeat,

When you save your changes though, all zone IDs for all the domains become the same zone ID, the first one chosen I believe.

<img width="925" alt="Screen Shot 2021-11-13 at 09 37 50" src="https://user-images.githubusercontent.com/18566096/141652131-38c39022-e8ba-4b8c-b4d7-2b45ca7602e0.png">

I already had figured out the trick to get them to save correctly, it was something like saving one domain at a time or something like that, however, the recent CA change of Let's Encrypt did a something that I was unable to renew them anymore, tests certs would pass but the real issuing wouldn't so I had to delete the cert and I can't remember the trick to get the challenges to save correctly, I tried changing commas for semicolons, removing spaces, saving in different orders; no luck--I assume the app wasn't designed for users to have to know tricks to make it work though so it think it's likely a bug.

Then again, I have been using an older version for a really long time though, and the fact that the bug's still there kinda makes me second guess if it's _really_ a feature...one that makes no sense. Oh well. just trying to help. :)

**Comment by webprofusion-chrisc** [comment]
Thanks for raising this issue, this was indeed fixed a few versions back (5.5.0, in July) so I'll re-test the current version to see if I can reproduce this, I assume you are on 5.5.7.

**Comment by webprofusion-chrisc** [comment]
So I've re-tested this but I haven't figure out how to reproduce it, so far I've:
- added one config at a time, saving between each one
- adding multiple in one go, saving once
- messed with the dropdowns and setting the challenge tyes back to http, back to dns again and changing the DNS API selection and back again.

If you are on the latest version can you give me a simple summary of how to reproduce the problem? It could be there is a certain way of working that makes it happen. It certainly was a bug before but the code has changed significantly since.

**Comment by webprofusion-chrisc** [comment]
Just as a follow up, this does not appear to be an issue in the latest version and I've been unable to reproduce this.
