### ISSUE TITLE
How to add more 3 domains...

### ISSUE THREAD

**Issue by jayjupdhig** [webprofusion/certify#594]
...as shown in that screenshot?

https://raw.githubusercontent.com/webprofusion/certify/development/docs/images/app-screenshot.png

**Comment by webprofusion-chrisc** [comment]
Hi, the community edition limit is 10 managed certificates (each certificate can cover up to 100 domains). After the first few certificates are added the app will display a "nag screen" i.e. a prompt to tell you that the software is commercial and you should generally consider using a licensed version, however if you click OK it will proceed to let you add another certificate (until it reaches the limit).

**Comment by webprofusion-chrisc** [comment]
General questions should be directed to https://community.certifytheweb.com/

**Comment by jayjupdhig** [comment]
Thank you very much for your feedback. Yes i know that it is a (limited) community edition - but after adding 3 domains (one of them with a www.-subdomain), the dialog to buy a licence was shown.

Are you really sure that the limit is 10 domain and not 3?

**Comment by webprofusion-chrisc** [comment]
Yes, the dialog will show but it does not then stop you adding the next managed certificate. Note that a domain is a not a certificate, so I assume you added 3 certificates (with one domain each). A certificate can cover multiple domains, not just one.

**Comment by jayjupdhig** [comment]
THank you.

**_"A certificate can cover multiple domains, not just one."_**

Maybe you can explain me that closer? I was thinking that was for subdomains only...?

**Comment by webprofusion-chrisc** [comment]
Yeah a certificate can cover any combination of domains and subdomains e.g. one certificate could be made to cover `example.com`, `www.example.com`, `somethingelse.com`,`webmail.somethingelse.co.uk`. 

The difficult part is in trying to validate all the domains at once in the same order, which is why we have the option to add multiple authorization configs (so for instance some of the certificate validation could be done using http validation and some other parts could be validated using dns validation).

**Comment by kosuodhmwa** [comment]
Thank you very much. (This is my personal account)
