### ISSUE TITLE
Add Infomaniak DNS API Provider

### ISSUE THREAD

**Issue by Cryotize** [webprofusion/certify#617]
Infomaniak provides an API for automated DNS Valdiation, services like [Traefik](https://doc.traefik.io/traefik/https/acme/#providers) have this already implemented. 
See: https://go-acme.github.io/lego/dns/infomaniak/

Would it be possible for you to implement this into certify? Thanks a lot for your great work!

**Comment by Cryotize** [comment]
Any Update or Information regarding this Issue?

**Comment by webprofusion-chrisc** [comment]
Hi! Sorry I missed this issue, yes we can integrate this in the future because Posh-ACME have a plugin and we already use many of their plugins.

However, this won't be integrated until our next update which is a major release and does yet have a planned release date. I would advise seeking an alternative workaround in the meantime.

**Comment by Cryotize** [comment]
Thanks a lot for the information!
