### ISSUE TITLE
How to run development environment?

### ISSUE THREAD

**Issue by Rainson12** [webprofusion/certify#629]
I am trying to run the certify project in VS2022 with .net Framework 4.6.2 as well as .netcore 7 installed however I keep getting plenty of issue like for example "Could not register named object. Cannot register duplicate name" for components used in the mainwindows.xaml ? Is there any documentation or guideline on how to start development?

**Comment by webprofusion-chrisc** [comment]
Hi, it should pretty much just build by opening the solution and building e.g. Certify.UI.sln so I'm not sure what the problem is. I'm working on a different branch and I generally use my own custom solution for the projects (which combines some things across repos) but I think these solutions should build ok. 

I find visual studio often doesn't like it if certain files are open (particularly XAML designer etc) during build and these do sound like XAML related errors.

What problem are you looking to solve with your build?

**Comment by DomiOh** [comment]
Not able to build it from scratch. Getting errors in masses. Like that a project from a folder named certify-plugins/Datastore cannot be found and the package restore fails.
![image](https://user-images.githubusercontent.com/7792161/229316251-7157f8e2-3294-42a6-96f3-b664fb10b188.png)

These are the error messages when trying to compile Certify.UI solution as Release, Any CPU build

**Comment by webprofusion-chrisc** [comment]
Thanks, that's a good point, there have been recent changes to plugin layout and related libraries and it works for me because I have the specific folder structure on disk. Create a folder such as certify_dev, then clone into that the certify repo and the certify-plugins repo, the solution is looking for that as a relative path for the SQLite database provider. You will soon also need a libs folder with a clone of https://github.com/webprofusion/anvil and the solution files will be moving under the certify\src folder

So the example folder structure is:

- certify_dev
  - certify
  - certify-plugins
  - libs\anvil

**Comment by DomiOh** [comment]
thanks for the answer. What is that error message with the determinism and the one with the missing XML namespace?

**Comment by webprofusion-chrisc** [comment]
Hi, when we do our dev/production build we generate a build props file to set the version info. I've added one to the repo now so if you just pull from the certify repo it should build ok. I've also updated the build info in the readme and confirmed that the instructions currently work.
