### ISSUE TITLE
Save button abnormalities

### ISSUE THREAD

**Issue by stephen-dunne** [webprofusion/certify#638]
v6.0.7

After saving changed cert connection auth details (btw the save appears to have worked, the change details are retained!) and leaving the saved cert for another one or to create a new one you are prompted again to save. This cycle continues again and again after saving each time.

Looks like the fact that the save has succeeded isn't being retained

**Comment by webprofusion-chrisc** [comment]
Thanks, I'll take a look. As part of the fix for #637 more events were hooked up to mark the model as changed, so you may find it depends which tab you are currently on.

Does it happen if you are only on the Status tab for a managed certificate or are you switch to the authorization tab first? As a workaround you can click "Discard changes" to just not save anything (since nothing has really changed). I think I've been doing this out of habit without realising.

**Comment by webprofusion-chrisc** [comment]
Thanks, there is a new release 6.0.8 which should resolve this issue, it would be great if you could check it out. Unfortunately our model for detecting and tracking changes has a lot of complexity which has resulted in some bugs recently (some of which were only recently discovered).

**Comment by stephen-dunne** [comment]
Nice one, it looks fine now with 6.0.8. Changing parameters causes the save button to become active, and once saved you don't get prompted again when switching to a different cert profile
