### ISSUE TITLE
Error when using Export Certificate task

### ISSUE THREAD

**Issue by PMillard5000** [webprofusion/certify#665]
I can successfully request a certificate from Lets Encrypt and deploy to the local certificate store.
But whenever i try and select the Export Certificate task to export the full certificate in pem format to a local folder it fails with access denied error.

I have tried with both local service and specified local credentials, but both fail.
When trying the deploy to CCS task using the same local target directory and the same service credentials it succeeds and exports a pfx certificate.

The error message given is the deployment task failed to complete. Export Certificate:: Failed to copy to destination file: xxxxxxxx : Access to the path xxxxxxxx is denied.

Have checked permissions and like i said it works to the same location using deploy to CCS using the same local service.
Any ideas?

**Comment by webprofusion-chrisc** [comment]
Hi, if you are a licensed customer you should send a support request with more specific details to support {at} certifytheweb.com

The most likely problem would be if you only specify an output folder and not a full file path. The certificate export requires a full path and filename otherwise you'd be trying to overwrite your folder with a file.

The PEM export is a conversion of the PFX to PEM component files, is there a specific password set on the PFX or are you just using the default (blank)?

**Comment by war59312** [comment]
It''s completely broken for me:

<img width="1325" height="826" alt="Image" src="https://github.com/user-attachments/assets/7899d418-a29a-4840-bf89-25e0062268e7" />

**Comment by webprofusion-chrisc** [comment]
@war59312 Community Support is here: https://community.certifytheweb.com/ or if you are a licensed customer then email support at certifytheweb.com with your log file. Whichever support channel you want to use (not closed github issues): what version of Certify Certificate Manager, do you have a working cert already and is there a PFX password set or is it default? [edit: and did you set a destination file path under Task Parameters]
