### ISSUE TITLE
Unable to make request if the server is unable to resolve the proper ip

### ISSUE THREAD

**Issue by jnc8651** [webprofusion/Certify#7]
Hello,

I have found if a server is behind a firewall that does not have nat hairpining configured properly then the request will fail. The workaround I have found is to make an entry in the hosts file pointing the proper ip to the domain that the request has been made for.

Jaime

**Comment by jnc8651** [comment]
In my instance I have subdomainA.domain.com pointing to ip 1.1.1.1 and the server's real internal ip is 192.168.1.2 the application does a dns lookup for subdomainA.domain.com and sees the ip is 1.1.1.1, the server will then attempt to connect to 1.1.1.1. Since the server is behind the firewall this will fail as nat hairpining has not been configured.  My current workaround is to make an entry in the windows hosts file for subdomainA.domain.com and have it resolve to 192.168.1.2

**Comment by webprofusion-chrisc** [comment]
Hi Jaime, the lets encrypt service verifies your domain/subdomain via the public internet. If they (letsencrypt) can't access the files that get created in the .well-known folder over http then your server can't use Certify to get ssl certs. You may have more luck with other windows clients that perhaps support dns challenges instead of http challenges.
