### ISSUE TITLE
FAQ: What to do in case /.well-known/ requires HTTP AUTH?

### ISSUE THREAD

**Issue by nathan-pmt** [webprofusion/certify#71]
I THINK this is being enforced by SmarterMail.

**Comment by ebekker** [comment]
Then it cannot be used to support HTTP method of validation.  Try DNS instead.

**Comment by webprofusion-chrisc** [comment]
Certify currently only supports the http-01 Lets Encrypt challenge type. So that means when lets encrypt wants to validate your domain it needs to make a request to your site over http on port 80 (not https). I'll try and get the TLS version happening soon but in the meantime you might find it more useful to use the ACMESharp powershell scripts directly (dns challenge type).

To get Certify to work you'd need to add http binding (port 80), you can remove the binding again but you will require it next time you need to validate your domain with Lets Encrypt (unless Certify gets TLS support before then).

**Comment by webprofusion-chrisc** [comment]
Closing. Not supported by http-01 method of domain verification.
